### ISSUE TITLE
Problems with the restart keyword

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-simulators#1060]
I am trying to run a restart of a simulation and I am obtaining an error.   I am actually running two versions of flow.  One from 6 months ago and the new version downloaded today.  The one from six months ago ran the restart without a problem but the new version creates the following error report.  

Restart Run with a version from july the 5th 2016.

![captura de pantalla de 2017-02-15 19-41-18](https://cloud.githubusercontent.com/assets/9252709/23002368/619a989a-f3b8-11e6-81a3-59d91d16fa66.png)

The same file run with the version from today.

![captura de pantalla de 2017-02-15 19-41-36](https://cloud.githubusercontent.com/assets/9252709/23002367/619a97aa-f3b8-11e6-9224-1dd8c9f46c3c.png)

And some more detail about the error
![captura de pantalla de 2017-02-15 19-41-51](https://cloud.githubusercontent.com/assets/9252709/23002366/61997014-f3b8-11e6-86e9-396f874bcd5c.png)

Could you please advice?  Both versions ran the basic simulation without any problem.

Kind regards,

David.

**Comment by atgeirr** [comment]
To be clear: did you try to run the current version of Flow with the *old* restart file, or did you create a new restart file?

We have added a lot more information to the restart files to improve restarting capabilities, one consequence is that old restart files do not provide all the information expected by newer versions of Flow. In fact, this situation will continue for a while, since we are not yet completely satisfied with restarting and will make more improvements in the months to come.

**Comment by joakim-hove** [comment]
> To be clear: did you try to run the current version of Flow with the old restart file, or did you create a new restart file?

Yes - that is a crucial question; if you ran new flow with old restart you would get exactly this brutal crash.

**Comment by dr-robertk** [comment]
Isn't there some form of version id for the restart files to capture these problems?

**Comment by joakim-hove** [comment]
> Isn't there some form of version id for the restart files to capture these problems?

No we do not have anything like that - the reason is an attempt to be as-compatible-as-possible with the ECLIPSE files. But of course we have already been forced to introduce `OPM_IWEL` and `OPM_XWEL` so we could of course also introduce `OPM_HEAD` which could contain among other things such a version ID. 

On the other hand - this is still very much development software, and this might be another thing to maintain for limited gain? I have no strong opinions on the matter.

**Comment by dlmorenob** [comment]
I ran the simulation with a flow version from two months, six months ago and a recent version.  Indeed the problem was between the old version of flow vs. the present one.  The one from two months ago worked fine.  I guess the restart file did not contain all the required fields during the read, the problem is resolved by running again the models on the latest version.  The problem is resolved.  Thank you.
