### ISSUE TITLE
Change policy when asking for summary output for unknown wells and groups. 

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1099]
Situations:

1. The `SUMMARY` section requests output for the wells and groups.
2. The `SCHEDULE` section has been edited - removing all well definitions and just inserting a couple of `TSTEP` keywords.

This is a quite common QC procedure to verify that the initial state is a true equilibrium. This will trigger an error in the output configuration, the behavior is governed by these `ParseContext` [switches] (https://github.com/OPM/opmparser/blob/master/opm/parser/eclipse/Parser/ParseContext.hpp#L222) where the current default behavior is to throw an exception. @alfbr wanted the default behavior to change to warning - I started on making that change e.g. [here](https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/FlowMain.hpp#L501) but I lost steam when I realized I had to search the code in at least five different `FlowMainxxx.hpp` files.

I understand that several `FlowMain` might be required, but really - the codebase should get a little more *not-very-exciting-refactoring* love and support.

**Comment by atgeirr** [comment]
It could be argued that the changed default behaviour is mostly relevant for the Flow family since for those simulators we are want to ease the path for engineers used to Eclipse. If you agree that is sufficient then there are just two places that need modification: the FlowMainBase class you already indicated above and (for flow_ebos) ebos/eclbasegridmanager.hh:141 in the ewoms module. Refactoring *that* is a question of significant differences in the approach to initialization and ownership of subobjects between the codes.

Hope that helps!

**Comment by atgeirr** [comment]
All merged, closing.
