### ISSUE TITLE
Multisegment well option and ICDs keywords in Flow

### ISSUE THREAD

**Issue by igorbagno** [OPM/opm-simulators#1100]
Hello, 

a question regarding the multisegment option in Flow. I've recently tried to implement it and it seems that the WELSEGS and WSEGDIMS keywords are accepted by the parser. When I try to introduce the COMPSEGS keyword (defining the completions in a multisegment well) the flow stops when launching. 

Is the multisegment option is supported by Flow in general?
And if yes, are the keywords describing the inflow control devices (ICDs) supported:
WSEGAICD, WSEGSICD, WSEGLABY and WSEFLIM?

Thanks and Regards,

Igor Bagno

**Comment by atgeirr** [comment]
Here is a summary of the situation around multisegment wells:
 - They are partially supported. In particular ICDs are *not* supported.
 - To use the support, you must use the "flow_multisegment" executable, not the "flow" executable.
 - There are some things that are better supported in the "normal" non-multisegment version of Flow.
 - We have concrete plans for unifying these separate programs, so that a single executable have all the capabilities. That will be completed this year.
 - We have looser plans for adding more capabilities such as ICDs. At this point we are not yet sure if we will do it this year.

Hope that helps you, and that the current flow_multisegment is sufficient for your immediate needs. If you are able to contribute something to this please tell us! For example, small testcases that we can include in our regular testing are very welcome.

**Comment by igorbagno** [comment]
Atgeirr, thanks for that. I'll definitely upload few examples with some emphasis on which functionalities would be good to see running. Can you advise, please, on where I can find the flow_multisegment executable?

Thanks!

**Comment by GitPaean** [comment]
The executable should be at the same folder with `flow`. Are you using the installed binary or you are building from the source?  For example, my build folder is `opm-simulators-buid` for `opm-simulators`, all the executables should be under the folder `opm-simulators-build/bin`. 

If you use the installed opm-binary, they should be under the system folder `/usr/local/bin`? Anyway, if you can run `flow`, you should be able to run `flow_multisegment`.

**Comment by igorbagno** [comment]
Kai, I use the installed binary. I run flow on Ubuntu 16.04 (Linux). Do you know if the flow_multisegment executable was build for Ubuntu?

**Comment by GitPaean** [comment]
Hi, I think `flow_multisegment` might not be included in the binary installation. 

Would you like to try compile from the source code? There is some instructions from http://opm-project.org/?page_id=231  

For Eigen, please install the one from the link https://github.com/OPM/eigen3    

I remember we got some problem using the eigen3 installed from Ubuntu, not totally sure what is the status related to this issue. 

If you have any problem in compiling, please let us know. We would definitely like to to help.

**Comment by alfbr** [comment]
> For Eigen, please install the one from the link https://github.com/OPM/eigen3

It will be installed automatically, just ensure that you do not have the Eigen installed by the distribution on your system.

**Comment by andlaus** [comment]
to me it looks like this issue has been answered? closing for now, feel free to reopen if necessary.
