### ISSUE TITLE
[Question] OPM terminal output formatting

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#1119]
I'm trying to rewrite some terminal output messages from Flow, to improve user readability. I've some questions and possible improvements within the same context. If you've worked on these messages before, please help me out with some clarifications and suggestion on the same:

1. Isn't it better to classify these messages(whenever there is a NaN value reported)  as a “Bug” , since these numerical issues are not normally supposed to occur?
        - eg. `msg = std::string("NaN residual for phase ") +  materialName(idx)`;

2. How can I modify the following messages to give the information of which(linear or non-linear) solver has failed? 
        - `msg = std::string("Solver failed to converge after ") + std::to_string(restarts) + " restarts.";`
        - `msg = "Solver convergence failed, restarting solver with new time step (" + std::to_string(unit::convert::to( newTimeStep, unit::day )) + " days).\n";`

3. I've stumbled across some "`OpmLog::Problem`" messages I cannot understand. Any suggestions on alternate output ? Also are these better classified as a ”Bug” or "Message" instead of a “Problem”? 
       -`errlog << "Obtain delta with non-finite value for Rs = " << Rs << " in the " << i << "th iteration     during finding saturation pressure iteratively";OpmLog::problem("wetgas NaN delta value", errlog.str());
`
       - `errlog << "Could find the oil saturation pressure for Rs = " << Rs;  OpmLog::problem("liveoil saturationpressure", errlog.str());`

4. Are the `logic_errors` and `runtime_errors` raised in `OPM_THROW` expected to cause a convergence failure or give an exit signal to the simulator?

Many Thanks,
Rohith

**Comment by atgeirr** [comment]
To each of your points:

1. I agree that NaNs should be treated as bugs, and such messages may be changed.
2. You cannot easily do that, since that information is not stored anywhere. At that point in the code, all we know is that something failed. However, the exception that was triggered has been logged to the debug file, see the catch blocks on lines 240-255. There you can see the exception messages etc. If this is insufficient you could set some kind of error code in the catch blocks and use that to modify the message. However, there is not a bijective mapping between exception types and causes of failure. For example, failure to solve the linear system can manifest as ISTLError, MatrixBlockError or a NumericalProblem. However, nonlinear solver failure also results in a NumericalProblem. We can improve this by changing what exceptions we throw and how we catch them, do you think that is necessary?
3. See OPM/opm-material#218 for a revision that changes those messages and reduces them significantly. I expect to merge it today.
4. That depends: with adaptive timestepping on (this is the default) we can handle problems by cutting the timestep. Any exception thrown from the step() call (from properties, assembly, linear solve, update etc.) will not result in early exit, but a timestep cut. Exceptions thrown under other circumstances will result in early exit.

**Comment by nairr** [comment]
@atgeirr Thank you for the clarification! 
> However, there is not a bijective mapping between exception types and causes of failure. For example, failure to solve the linear system can manifest as ISTLError, MatrixBlockError or a NumericalProblem. However, nonlinear solver failure also results in a NumericalProblem. We can improve this by changing what exceptions we throw and how we catch them, do you think that is necessary?

@alfbr  - Do you have any comments regarding this?

**Comment by alfbr** [comment]
Yes I do. Sorry for not responding earlier, Easter caught up with me. I believe we should put in the effort to have exceptions that separate NumericalProblem so that we can log-messages separating a linear convergence problem from a non-linear convergence problem. Further, I believe we should keep in mind that we do want to be in a position where we can start lgging advices to users on how convergence can be improved by changing numerical tuning parameters. Hence, we should ensure that we obtain enough information from the exceptions thrown to identify what numerical tuning parameters might remedy the situation.
