### ISSUE TITLE
flow_ebos broken in parallel due to wrong keyword treatment.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1143]
When running Norne with flow_ebos in parallel we are experiencing well curves that are in parts a bit shifted and wrongly scaled. I did some tests with modified Norne decks and it turns out that the major part of the problems vanish if I disable MINPV, PINCH, ENDSCALE, HYSTERIS and maybe more.

Here is the diff:
```
$ diff NORNE_ATW2013.DATA NORNE_ATW2013_NOENDSCALE.DATA
29,30c29,30
< ENDSCALE
< NODIR   REVERS /
---
> --ENDSCALE
> --NODIR   REVERS /
34,35c34,35
< SATOPTS
< HYSTER  /
---
> --SATOPTS
> --HYSTER  /
336,337c336,337
< EHYSTR
<    0.1   0  0.1 1* KR /
---
> --EHYSTR
> --   0.1   0  0.1 1* KR /
339,351c339,351
< COPY
<  'SWCR'  'ISWCR'   1 46 1 112  5  22 /
<  'SGU'   'ISGU'    1 46 1 112  5  22 /
<  'SWL'   'ISWL'    1 46 1 112  5  22 /
<  'SWU'   'ISWU'    1 46 1 112  5  22 /
<  'SGL'   'ISGL'    1 46 1 112  5  22 /
<  'SOGCR' 'ISOGCR'  1 46 1 112  5  22 /
<  'SOWCR' 'ISOWCR'  1 46 1 112  5  22 /
<  /
< 
< EQUALS
< ISGCR 0.22 1 46 1 112  1  22 /
< /
---
> -- $$$ COPY
> -- $$$  'SWCR'  'ISWCR'   1 46 1 112  5  22 /
> -- $$$  'SGU'   'ISGU'    1 46 1 112  5  22 /
> -- $$$  'SWL'   'ISWL'    1 46 1 112  5  22 /
> -- $$$  'SWU'   'ISWU'    1 46 1 112  5  22 /
> -- $$$  'SGL'   'ISGL'    1 46 1 112  5  22 /
> -- $$$  'SOGCR' 'ISOGCR'  1 46 1 112  5  22 /
> -- $$$  'SOWCR' 'ISOWCR'  1 46 1 112  5  22 /
> -- $$$  /
> -- $$$ 
> -- $$$ EQUALS
> -- $$$ ISGCR 0.22 1 46 1 112  1  22 /
> -- $$$ /
366c366
< 'IMBNUM'  2    1  46  1   112    1  22  /
---
> -- 'IMBNUM'  2    1  46  1   112    1  22  /
$
```
With these changes the curves are not perfect but for the most part pretty close.

@andlaus, how are these keywords handled in flow_ebos and where in the code. Any clues what could go wrong?

I guess for flow_mpi these issue were automatically handled by setting up the properties on the global grid and the scattering the data to the distributed grid.

**Comment by andlaus** [comment]
These keywords are handled by `EclProblem` and `EclMaterialLawManager`. Since all of the satfuncs stuff  is intensive, the distributed init is almost certainly not the culprit. Possibly, you have an issue with synchronizing the solution (and/or the reservoir state object?!) after each Newton-iteration, so that processes desynchronize on non-interior cells. alternatively, the hysteresis update is possibly only done for interior elements instead of all of them.

the MINPV/PINCH keywords are mainly handled by the grid, just the adaptation of the pore volume is done by [`EclProblem`](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L1052-L1069). Since that piece of code only uses the logically Cartesian data for potentially inactive non-local elements, and this data is directly obtained from `EclipseState`, I think that your problem description points towards a bug in `Dune::CpGrid` if this is the cause for the discrepancies which you observed.

**Comment by andlaus** [comment]
ok, the hystersis parameters where indeed not updated on ghost and overlap elements: OPM/ewoms#170 should fix it. @blattms: does this fix your issue? if yes, I'll cherry-pick the patch into the release branch.

**Comment by blattms** [comment]
> I think that your problem description points towards a bug in
> `Dune::CpGrid` if this is the cause for the discrepancies which you
> observed.

In that case I would assume that I see similar problems with flow_mpi,
wouldn't I? But I do not.

**Comment by andlaus** [comment]
with OPM/ewoms#170 I can run Norne with 6 processes and get virtually indistinguishable results as for the sequential run, just in less than 5 minutes instead of almost 12 for the sequential run and 6.5 minutes for flow_mpi with 6 processes. interestingly, flow_ebos sees considerably fewer convergence problems than flow_mpi but the linear solver still  takes about one minute longer than for flow_mpi. (for that scenario, the linear solver used more than 75% of the time with flow_ebos.)

**Comment by blattms** [comment]
great! Thanks for testing.

**Comment by andlaus** [comment]
The lion's share is yours for analyzing this issue. thanks a lot!
