### ISSUE TITLE
2017.10 version - flow returning error

### ISSUE THREAD

**Issue by igorbagno** [OPM/opm-simulators#1426]
Hello,

I've upgraded opm simulators for Ubuntu 16.04 with the 2017.10 release.

Now getting a following error when launching flow:
```
flow: symbol lookup error: /usr/lib/x86_64-linux-gnu/libopmparser.so.2017: undefined symbol: _ZN3ERT11smspec_nodeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKii
```
Also noticed an issue with the following package:
libecl1_2017.10-rfinal-2~xenial_amd64.deb

dpkg returns the following error when installing it:
```
Errors were encountered while processing: libecl1_2017.10-rfinal-2~xenial_amd64.deb
```
Thank you in advance for support!

Kind Regards,

Igor

**Comment by atgeirr** [comment]
Could you post the error message you get from dpkg, it could perhaps tell us something? Also, forgive my ignorance, but if you are on Ubuntu, I would assume that using the apt tools would be the usual way to install packages, did you use dpkg directly for a particular reason?

Since your upgrade did not go smoothly, I suggest you try to uninstall all opm, ecl and dune packages, and reinstall. Any further ideas @akva2?

**Comment by akva2** [comment]
that will be the issue. due to the libecl stuff, we do not cleanly update from older versions. remove everything, the reinstall using apt (or dpkg if absolutely necessary). the trick is getting rid of libert.ecl(1|-dev)

**Comment by igorbagno** [comment]
atgeirr, thank you for your prompt reply

I get the following error message from apt-get when trying to install libecl1:

Errors were encountered while processing:
 /var/cache/apt/archives/libecl1_2017.10-rfinal-2~xenial_amd64.deb
**E: Sub-process /usr/bin/dpkg returned an error code (1)**

I'll follow your advice to remove opm, dune and ecl packages and reinstall again. 
I'll let you know how it goes.

Thank you

Kind Regards,

Igor

**Comment by blattms** [comment]
Closing as this is about really old packages
