### ISSUE TITLE
Opm::StandardWell<xxx>::addWellContributions(Matrix&) not found

### ISSUE THREAD

**Issue by kingaj12** [OPM/opm-simulators#1435]
I just cloned the latest opm-simulators and I am getting the subject error.  It appears that the flow_ebos_xxx.cpp in opm/simulators needs this method, but I can't figure out why.

**Comment by GitPaean** [comment]
Hi, this code was introduced recently in this PR https://github.com/OPM/opm-simulators/pull/1183 . To be honest, I am not very familiar with it. It is supposed to have no effects when running with default parameters. 

Anyway, if you can provide a little more information, like the deck, and running arguments, so that I can reproduce your problem, I would be willing to help you to address this issue.

**Comment by kingaj12** [comment]
Hi - thanks! I am trying to build flow, but I can't link.  Here is the error:

lib/libopmsimulators.a(flow_ebos_blackoil.cpp.o):  
 (.data.rel.ro._ZTVN3Opm12StandardWellIN5Ewoms10Properties4TTag14EclFlowProblemEEE[_ZTVN3Opm12StandardWellIN5Ewoms10Properties4TTag14EclFlowProblemEEE]+0x88): undefined reference to 
 `Opm::StandardWell<Ewoms::Properties::TTag::EclFlowProblem>::addWellContributions(Dune::BCRSMatrix<Dune::FieldMatrix<double, 3, 3>, std::allocator<Dune::FieldMatrix<double, 3, 3> > >&) const'
    
It looks like StandardWell::addWellContributions is missing.  When I do a search over the whole body of code (including the required packages like opm-common, etc) I don't find any uses of addWellContributions except in `opm/autodiff/BlackoilWellModel.hpp`

    void addWellContributions(Mat& mat)
            {
                for ( const auto& well: well_container_ ) {
                        well->addWellContributions(mat);
                }
            }

I tried commenting out this piece of code, but I still get the same issue.

**Comment by GitPaean** [comment]
Hi, the function is defined in the following location of StandardWell_impl.hpp, line 2113.

https://github.com/OPM/opm-simulators/blob/79bc265de8de4737a807f4772970fba1c4cb558b/opm/autodiff/StandardWell_impl.hpp#L2113

It looks weird to me and I am not sure what is the problem. I suppose you did not make any modification of the code. 

Did you manage to compile  opm-common, opm-material, opm-grid, ewoms successfully before opm-simulators? 

Due to recent PRs https://github.com/OPM/opm-common/pull/341 and https://github.com/OPM/opm-simulators/pull/1386, opm-parser, opm-output and opm-core has been removed from the dependence tree. 

Now you only need to compile opm-common, opm-material, opm-grid, ewoms and opm-simulators to use `flow`. 

Please tell a little more about how did you try to build flow with some more details, like instructions and system, did you use any IDE software? We can try to see if anything missing there.  It is late here now, response will be tomorrow.

**Comment by kingaj12** [comment]
ok - I will post more details tonight.

**Comment by kingaj12** [comment]
I refreshed the download and built only the modules opm-common, opm-material, opm-grid, ewoms and opm-simulators as you suggested.  It seems to be working fine now.

It is possible that something I did in the transition from a dev thread to a forked thread made something go wrong.  Anyway, I redid the move and now it is fine.  

Sorry for the bother.
