### ISSUE TITLE
Flow Crashes in Checked Iterator/Debug Build Running SPE1CASE1

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#1453]
It's been a while since I tried to run a checked iterator/Debug build of flow so I don't know if this is a new issue or if it simply has not been reported before.

Earlier today I tried to run
```
${flow} deck_filename=${spe1case1} output_dir=./spe/1/case1
```
with `${flow}` pointing to a checked iterator build (`-O0 -ggdb3 -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1`) of `flow` and `${spe1case1}` being the full path to [SPE1CASE1.DATA](https://github.com/OPM/opm-data/blob/master/spe1/SPE1CASE1.DATA) from the opm-data repository.

This simulation run crashed on the second time-step (i.e., "ministep" index 1 within report step 0) with an "index out of bounds" exception on line [1091](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L1091) of `ewoms/ebos/eclproblem.hh`.  If I locally disable the portion of `Ewoms::EclProblem<>::endTimeStep()` that [discards the `initialFluidStates_`](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L661-L663), then I can run the checked iterator build to completion.  I do however not know if disabling that section is just papering over some other issues so I'd like a little input from parties that know that area of the code better than I do.

**Comment by atgeirr** [comment]
To me this looks like a simple bug: the temperature() method should probably access some potentially time-varying field instead of the initial temperature, that looks like a placeholder from before the thermal stuff was implemented. That said, why is this method called at all when running SPE1?

What do you think @andlaus?

**Comment by andlaus** [comment]
> That said, why is this method called at all when running SPE1?
>
> What do you think @andlaus?

My first hunch is that it is related to output. I'll investigate.

**Comment by bska** [comment]
>> That said, why is this method called at all when running SPE1?
> 
> My first hunch is that it is related to output. I'll investigate.

Just for reference, I uploaded a GDB backtrace to [Gist](https://gist.github.com/bska/9bd81d3a03e3c4866e516cbead138ef7).  Frame 11 stands out as being a call to
```
Ewoms::FvBaseAdLocalLinearizer<Ewoms::Properties::TTag::EclFlowProblem>::linearize
```
That looks a bit like we end up in `temperature()` when assembling the linear operator during a non-linear iteration.

**Comment by andlaus** [comment]
I've just checked: it does not happen for optimized builds and also not for "normal" debug builds, but only if `-D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1` are set. anyway, the bug is caused by accessing the initial fluid state to retrieve the temperature for non-thermal situations. OPM/ewoms#311 fixes it.

**Comment by bska** [comment]
> OPM/ewoms#311 fixes [this issue].

Confirmed.  The checked iterator build runs to completion when I apply OPM/ewoms#311.  Thank you for the expedient patch.
