### ISSUE TITLE
libecl: update required for integration tests

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1486]
I just posted this to the mailing list; but it does not seem to go through?

```txt
I have just merged three PR's listed below. Following this merge 
you will need to update libecl to get correct numerical values for
some of the integration tests in opm-simulator. The change is a 
preparation to change the volume calculation used in OPM.

https://github.com/OPM/opm-common/pull/407
https://github.com/OPM/opm-tests/pull/19
https://github.com/Statoil/libecl/pull/411
```

**Comment by alfbr** [comment]
That is because you have a new e-mail address. It is now added, so you do not need to do anything. For others, we get so much spam, so registering by subscribing is a necessity to keep the list tidy. You should get an e-mail informing you about it if you try sending from an unregistered e-mail address.

**Comment by joakim-hove** [comment]
> That is because you have a new e-mail address. It is now added, so you do not need to do anything.

OK - thank you!

**Comment by blattms** [comment]
Old news about changing libecl. closing
