### ISSUE TITLE
Feature Request: DEBUG Name Change

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1504]
Change the name of the the debug output file from .CASNAME.DEBUG to CASENAME.DBG to conform to the commercial simulator's behavior.

**Comment by atgeirr** [comment]
I am in favour of this, although the original reason for making it a hidden file (starting the filename with a period) was that engineers would not expect nor want to see this file. However, if Eclipse now generates a .DBG file I think it is reasonable for us to do so as well, unless that file has particular uses in workflows (meaning that we must make an equivalent file, rather than just dumping our own debug output there).

**Comment by atgeirr** [comment]
@alfbr Your people are ok with this?

**Comment by alfbr** [comment]
Yes, I think so. There has been no requests for a .DBG file, so I believe it is safe to use it for our debug file. Thumbs up here.
