### ISSUE TITLE
problem in creating summary, init, egrid, 

### ISSUE THREAD

**Issue by missmdas** [OPM/opm-simulators#1576]
on running any of all the OPM decks ........ none of the .init, .egrid, .unsrt, .unsmry files are being created...... what might be the problem

**Comment by bska** [comment]
May I ask the exact command (including name of executable and all filepaths), you use to run the simulation?

**Comment by andlaus** [comment]
I also can only speculate, but I guess you're looking for these files at the wrong place: because it was explicitly requested by an important stakeholder in no uncertain terms, all result files are written to the same directory as the input file by default. you can change this to the current directory by specifying  `output_dir=.` (for OPM 2018.04 and before) or `--output-dir=.` (for the master version) on the command line.

**Comment by missmdas** [comment]
Thank you..... but now I know what was going on....... i was using windows and ubuntu both in my system....... and files being created are hidden in windows side unless the host command is used......
