### ISSUE TITLE
Flow continue with run when an ilegal option is speficed on command line

### ISSUE THREAD

**Issue by tskille** [OPM/opm-simulators#1813]
I have learned that the simulator will continue with the simulation when the user has specified an an option on the command line which is not valid. The simulator will print a warning to standard output (Unrecognized parameters). This information will be visible on the screen for a very short time. In addition a list of unused run-time specified parameters is printed to the PRT file.

**In my opinion, the run should not start in this case.** If the user tries to make a run using an option which doesn't exists, the application should stop and inform the user. This is typical what any command line application would do.

**Comment by totto82** [comment]
I agree. I have wasted some time on silly spelling mistakes due to this.

**Comment by OPMUSER** [comment]
@tskille  +1 from me.

If you want easier an way to run OPM Flow you can try OPMRUN that puts a GUI on OPM Flow and allows you to edit the command line parameters through the GUI.  The program just parses the help from OPM Flow  and allows you to edit all the parameters via the GUI, it then writes out the param file for the job.

It looks like this:

![Clipboard_data](https://user-images.githubusercontent.com/17958927/57076179-94d45a00-6d1b-11e9-915e-2023c8e34e38.jpg)

The program also allows to you create queues so that you can run a bunch of jobs sequentially . It's written in Python so you can play around (or change it) as you like. Some people have complained that it will not work on their machine; however, I have created a binary version that runs without any problems.

You can find the software here https://github.com/OPM/opm-utilities/tree/master/opmrun

If you need the binary let me know. Also any suggestions on improving the software will be warmly appreciated.

**Comment by GitPaean** [comment]
I guess this should be closed by #1840. Feel free to reopen it if the problem still exist.

**Comment by blattms** [comment]
The successor #1845 of #1840 is not yet merged. Please only close when it is merged (should probably happen automatically.

**Comment by GitPaean** [comment]
Sorry. I did not see #1840 is not merged. And I got the wrong impression that un-recognized keyword can terminate running now. A testing show it terminates the running only for wrong format not unrecognized keywords.

**Comment by blattms** [comment]
Fixed with #1845
