### ISSUE TITLE
Group behavior bug exposed in test SPE9_CP_GROUP?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1943]
The deck in the test SPE9_CP_GROUP test contains:
```
-- The total rates is set to 1500 STBO 
GCONPROD
--      oil   water  gas
   'F'    'LRAT'  3* 1500 /
   'A'    'FLD'   4* 'RATE' 'YES' 1 'OIL' /
/

GEFAC
    'A' 0.85 /
/

GCONINJE
 'A' 'WATER' 'VREP' 3* 1 /
/
```
I.e. the group `A` is registered both as a producer with `GCONPROD` and then afterwards as an injector with `GCONINJE`, in the previous opm-common implementation that would result in both `group.isInjector()` and `group.isProducer()` returning true - seems dubious?

Discovered while working with: https://github.com/OPM/opm-common/pull/894

**Comment by GitPaean** [comment]
in theory, a group can have both injectors and producers. it depends how we gonna use it, maybe we can change the name of the functions to be `hasInjectors()` and `hasProducers()`. 

Anyway, it will depend on our implementation. Not sure `isInjector()` and `isProducer()` are making any problems.

**Comment by bska** [comment]
Any updates here?  Do you, @joakim-hove, still view this as a problem in light of @GitPaean's [comment](https://github.com/OPM/opm-simulators/issues/1943#issuecomment-511788494)?

**Comment by joakim-hove** [comment]
I still think this is suspicious - but I am no expert on the topic.

**Comment by GitPaean** [comment]
Since you can specify both `GCONPROD` and `GCONINJE` to the same group, basically it means the group can both inject and produce at the same time.  For example, with the example you posted, the group has a oil production rate target, at the same time, it has a injecting target based on reservoir voidage replacement (VREP).

I do not see why ` both group.isInjector() and group.isProducer() returning true ` is a big problem at all.  If there is some problem, it is the bad naming of the functions.  (I just saw the function names are actually (changed recenlty?) `isProductionGroup` and `isInjectionGroup`, which is better, since it distinguishes itself from the two function names from the `Well`).

We might need to update the implementation in some way to handle corner situations. For example, what we will do if we use `GCONPROD` for a group that only contains injectors? A good understanding of these types of corner situations might help us to give a better definition of function  `isProductionGroup` or even helps us to have a better function name and implementation. 


For a well, the situation is different. If we specify `WCONPROD` and `WCONINJE` for the same well, only the latest `WCON*` can work. A well can no way inject and produce at the same time (maybe with zero rate target?). As a result, for a well, you can not have both `isProducer` and `isInjector` to be true.

**Comment by joakim-hove** [comment]
@gitpaen - you seem to be totally relaxed about this, maybe I am exaggerating - but to me it seems very weird with the groups which are controlled with both GCONPROD and GCONINJE?

**Comment by GitPaean** [comment]
> but to me it seems very weird with the groups which are controlled with both GCONPROD and GCONINJE?

Because for some reason, we put some production wells and injecting wells at the same group, which might be necessary for a flexible grouping strategy. Especially for multi-level group structure, this flexibility might be necessary. We do not necessarily always want to use `production` or `injection` as one of our grouping criterion.

For example, if our grouping criteria is based on physical region. We want to put all the wells in the same region to be a group. If we can not allow producers and injectors in the same group, then there is no way we can put them in the same group. We need to have at least two groups to handle them. 

Let us go to a little extreme side, the group `FIELD`. For most of cases, it has to contain both injectors and producers. What if we want to give the `FIELD` a producing target and an injecting target?   

For the example you posted, we have pretty comparable results with the commercial simulator.

**Comment by GitPaean** [comment]
Most likely, we will have various changes in the group related implementations in the not far future. However, the issue reported here does not have principle problems to me.

**Comment by joakim-hove** [comment]
> What if we want to give the FIELD a producing target and an injecting target?

Yes - that is the core question, can opm/flow solve that problem in a meaningful way?

Mind you - I would be more than happy to be caught crying wolf here, I just find the alleged behavior quite surprising.

**Comment by GitPaean** [comment]
> Yes - that is the core question, can opm/flow solve that problem in a meaningful way?

We have something wrong implementation related to `FIELD` group.  So the answer is NO. 

But for the group `A` you posted, which has both producing target and injecting target, the results of the opm/flow is reasonable and reflect the correct behavoir comparing with the commercial simulator.

**Comment by GitPaean** [comment]
>  I just find the alleged behavior quite surprising.

If we think about it with the same way with `Well`, it can be surprising.

 But a group has some different characters from a `Well`. Being able to inject and produce at the same time is the key one related to this issue.

**Comment by OPMUSER** [comment]
Just to be clear, it is very common to have the same group (including the group at the field level), to be under both group production and group injection control. For example, in an oil model under water flood one normally sets the injection rate to be a function of the in situ withdrawal rate, that is the voidage replacement ratio is set to 1.0 in order to maintain the reservoir pressure. The only way to do this is to set both the injection and production targets for the same group.

**Comment by joakim-hove** [comment]
OK @GitPaean and @OPMUSER - thank you for clarifying this. I am sorry for the noise.
