### ISSUE TITLE
ecl_summary does not generate new results after new run

### ISSUE THREAD

**Issue by jeosol** [OPM/opm-simulators#1947]
I am experiencing a weird issue when running ecl_summary for a new case. For testing to ensure that the deck is correct, I run a small simulation, e.g., a few days. Then afterwards, I increase the total simulation time (e.g., 2000 days) and when I run ecl_summary on the new run, I still results from the old run (with a few days.) The longer-run simulations do run till completion but the results don't get updated.

Any reasons for this behavior?

**Comment by joakim-hove** [comment]
The results on disk are only updated when a report step has completed, if the long simulation has not completed a full report step that would explain it. Otherwise - don't know right away.

**Comment by jeosol** [comment]
Both runs did complete. I have experienced this issue a few times and it may be a change that makes things not updated. 

I'll copy the deck to a different name and modify from there. Thanks Joakim. I'll close this.

**Comment by OPMUSER** [comment]
OPM Flow, unlike the commercial simulator, does not delete the previous run output files, so it is possible to have this happen for a variety of reasons. I you use OPMRUN to submit your jobs it cleans up the output files first and then runs OPM Flow, in order to avoid these type of issues.  If you don't want to use OPMRUN you could use a shell script to do the same thing.
