### ISSUE TITLE
Wither restart - opinions please!

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#2359]
As described here: https://github.com/OPM/opm-common/issues/1396 there is currently work ongoing to be able to restart the simulator in situations where don't have access to the historical schedule file. That capability is currently needed within Equinor.

This issue is about what we should do in situations where we have the historical schedule file, i.e. the only situation we can currently restart from. My initial plan was to change the behavior so that the historical restart section was unconditionally ignored in the case of a restart - that is in accordance with how Eclipse does it, and certainly give many dog-food points. However initializing the `Schedule`object purely from the restart file is complex, and if we just over night change to that approach it is certainly possible we end with a regression - not being able to restart a model which we have previously been able to restart - that would be unfortunate.

So - all in all I am currently leaning towards using the historical schedule file - if we have it. It could be configurable (compile time / run time ??); and also we could *plan* to move in the direction of unconditionally using only the restart file to initialize the `Schedule` object.
 
Opinions?!

**Comment by OPMUSER** [comment]
My preference would be to follow the commercial simulator straight away, combined with testing as many models as possible before the release. Its already confusing having two types of restart files and methods for restarting, the quicker we move to the industry standard the better.

Just my two cents.

**Comment by joakim-hove** [comment]
> My preference would be to follow the commercial simulator straight away

I agree that would be the best - but it is also the most risky alternative.

>  Its already confusing having two types of restart files and methods for restarting

Mind you - this is not about the format for the restart files; it is whether we should use them (irrespective of OPM extensions) to initialize the well and group description, or if we should prefer the historical schedule input - when it is available.

**Comment by jalvestad** [comment]
There are several Schedule data options in E100 that imply dynamic changes to Schedule objects during the simulation and that are not captured by the Schedule data input, but which are stored in the Eclipse-compatible Restart file. Examples of this are: i) Changes to wells etc. due to ACTIONX data (e.g. shutting and opening of wells etc.), ii) Changes to wells using GCONPROD and for procedure on exceeding a maximum rate limit set to WELL (which is used by relevant assets), PLUG - plugging  back worst-offending well, and even CON (or +CON) which  means shutting off connections, and iii) WECON (and GECON - not used in flow yet) which can cause shutting in well or shutting off connections. 

The main point here is that flow, when doing a restart run, needs to be able to load the correct Schedule data from the Restart file and this means in practice that flow needs to be able to do a restart from a Restart file and not from reading the Schedule input deck - even to handle properly the functionality that is currently implemented in flow.

It should be noted that E100 always reads the VFP-tables from the input Schedule deck, so I think flow should also have a similar SKIPREST functionality as E100 in order to read input files used by E100.

**Comment by joakim-hove** [comment]
> i) Changes to wells etc. due to ACTIONX data (e.g. shutting and opening of wells etc.), [...]

Thank you for setting this straight. Yes - I agree we must be able to restart based *only* on the restart file. I think I will suggest an interim period with an alternative based on the SCHEDULE file - if it exists.

**Comment by OPMUSER** [comment]
@jalvestad SKIPREST is already implemented and works.

**Comment by OPMUSER** [comment]
@joakim-hove 

> Mind you - this is not about the format for the restart files; it is whether we should use them (irrespective of OPM extensions) to initialize the well and group description, or if we should prefer the historical schedule input - when it is available.

We should always use the RESTART file not the input deck SCHEDULE section. Many years ago before SKIPREST was implemented, one had to delete all the SCHEDULE data (except the VFP tables) up to the restart point in order to restart a run. So we should never use the SCHEDULE data prior to the RESTART date.

Hence, my preference to follow the commercial simulator straight away, as this is the correct way to restart a run. Remember in a full field model this type of discrepancy will be hard to track down and may explain difference between the commercial simulator and OPM Flow.

**Comment by joakim-hove** [comment]
> We should always use the RESTART file not the input deck SCHEDULE section. 

OK - the arguments are quite clear - the end goal is to use only the restart file. This is a quite significant change; so I will argue quite vehemently for having an intermediate period with a switch of some sort.

**Comment by atgeirr** [comment]
> OK - the arguments are quite clear - the end goal is to use only the restart file. This is a quite significant change; so I will argue quite vehemently for having an intermediate period with a switch of some sort.

At this point we cannot restart from only the restart file, if I understood this correctly, so until that is implemented we have no choice. But from the moment that code is available, tested and working correctly, I see no reason to keep the other option? (And if there is a reason, it should not be the default behaviour.)

**Comment by joakim-hove** [comment]
> At this point we cannot restart from only the restart file, if I understood this correctly, so until that is implemented we have no choice.

That is correct - but work is underway to be able to restart only from the restart file.

> But from the moment that code is available, tested and working correctly, I see no reason to keep the other option?

That we agree - but; seeing that writing proper restart files has been going on for years - and still is; my hunch is that we will experience some temporary setbacks in the restart from restart file functionality - to the extent that having an alternative makes sense - IMHO.

**Comment by alfbr** [comment]
> But from the moment that code is available, tested and working correctly, I see no reason to keep the other option?

I believe "tested and working correctly" is the key point. We all need to test properly to ensure that existing functionality is not lost. The faster we can square that off, the faster we can transition to only restart from restart files. As I understand, @joakim-hove wants to avoid a situation where critical functionality is broken for users, while fixes may be hard to track down and fix in a timely manner. It just means that the rest of us needs to step up and test properly on the cases we support :-)

**Comment by akva2** [comment]
if by 'step up and test properly' you mean 'step up and write tests before we change sensitive code', i concur.

**Comment by alfbr** [comment]
> if by 'step up and test properly' you mean 'step up and write tests before we change sensitive code', i concur.

I should have seen that coming :-) You have a very strong point, we need to strengthen the tests with respect to restart functionality.

**Comment by joakim-hove** [comment]
Clear message received - closing
