### ISSUE TITLE
boost::filesystem still a dependency?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2509]
It seems like the FlexibleSolvers still depend on boost::filesystem as they are using [`boost::property_tree::read_json`](/OPM/opm-simulators/blob/4a6814d6bc361f08babc558253d6b3a021cb5bea/opm/simulators/linalg/setupPropertyTree.cpp#L41). At least on my system the property tree depends on filesystem.

**Comment by akva2** [comment]
sadly yes. we can't do anything about internal dependencies in boost..

**Comment by atgeirr** [comment]
Upon checking my boost lib, I do not see any such dependency, by checking the includes at least. There are no includes that include the words "file" or "path". Are you sure this is the case?

**Comment by blattms** [comment]
My package manager says there is a dependency. I did not check further.

**Comment by blattms** [comment]
Did you check the source files, too? Wow!

**Comment by atgeirr** [comment]
> Did you check the source files, too? Wow!

Actually, only the headers, assumed there were no source files since there is no lib for it. But I got nervous about that assumption, so I downloaded the latest boost (754 MB unpacked!) and checked the property_tree, and there are no filesystem deps.

There are others, however, such as serialization, but I think that will only be used if you include it (not checked carefully). Tested compiling one of the examples (speed_test.cpp) with no linking, and that works fine, so I think it is safe to assume it is header-only, at least as we use it.

**Comment by blattms** [comment]
ldd thinks so, too:
```
mblatt@smaug:~/src/dune/opm-2.6/opm-simulators/opm-parallel/bin$ ldd flow | grep boost
	libboost_date_time.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.67.0 (0x00007f423df74000)
	libboost_system.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.67.0 (0x00007f423b310000)
mblatt@smaug:~/src/dune/opm-2.6/opm-simulators/opm-parallel/bin$ ldd flow_blackoil_dunecpr | grep boost
	libboost_date_time.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.67.0 (0x00007f1fafe12000)
	libboost_system.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.67.0 (0x00007f1fad1ae000)
```
But it is not the FlexibleSolvers fault.

**Comment by blattms** [comment]
I should learn how to read. There is no filesystem there.
