### ISSUE TITLE
Long output write time for Egg case on WSL2

### ISSUE THREAD

**Issue by moyner** [OPM/opm-simulators#2545]
I have Ubuntu 18.04 installed in Windows Linux Subsystem 2 and installed flow via the ppa. When running the Egg model I get a large amount of time spent in the output write time:
`flow --threads-per-process=1 --output-mode=none --enable-ecl-output=false BENCH_EGG.DATA`
> ================    End of simulation     ===============
> Number of MPI processors:      1
>Threads per MPI processor:     1
> Total time (seconds):         191.506
> Solver time (seconds):        191.322
> Assembly time (seconds):     16.2909 (Failed: 0; 0%)
> Linear solve time (seconds): 23.4811 (Failed: 0; 0%)
> Linear solve setup time (seconds): 0.602405 (Failed: 0; 0%)
> Update time (seconds):       0.885608 (Failed: 0; 0%)
> Output write time (seconds): 149.42
> Overall Well Iterations:      0 (Failed: 0; -nan%)
> Overall Linearizations:       608 (Failed: 0; 0%)
> Overall Newton Iterations:    472 (Failed: 0; 0%)
> Overall Linear Iterations:    9559 (Failed: 0; 0%)
If I run without ECL output, it fixes the issue (but I do not get any output!)
`flow --threads-per-process=1 --output-mode=none --enable-ecl-output=false BENCH_EGG.DATA`
> Output write time (seconds): 0.997147
If I disable async output, the time goes up significantly. The DATA file contains the following relevant output keywords:

UNIFOUT

RPTSOL
 RESTART=2 /
/

And in SCHEDULE:
RPTSCHED
    FIP WELSPECS WELLS /

RPTRST
   BASIC=2/

I do not get the same amount of write time on other cases (NORNE, a larger syntethic case, both 3ph).

**Comment by bska** [comment]
Are you by any chance using the 2019.10 OPM Flow release?  There was a file writing performance regression fairly recently which @atgeirr fixed in PR OPM/opm-common#1264 (commit OPM/opm-common@e4e3b3bde).  I don't think that fix made it into the 2019.10 release, but it will be available in the upcoming 2020.04 release.

For what it's worth I'm getting the performance results quoted below on the EGG case when running natively on a Ubuntu 18.04 LTS laptop using current master development sources of the simulator.  As the model creates restart output on each step (`BASIC=2`) there is considerable seeking involved if you don't have the fix from OPM/opm-common#1264.  You'll notice that the output time is about 3% of total runtime, but that the number of linearizations and Newton iterations is higher than you report.  The latter is slightly concerning and might call for some investigation on the OPM project's part.

Do you get different behaviour if you temporarily disable unified output (`UNIFOUT`)?

--- 

```
Number of MPI processes:      1
Threads per MPI process:      1
Total time (seconds):         67.8984
Solver time (seconds):        67.8286
 Assembly time (seconds):     27.4949 (Failed: 0; 0%)
 Linear solve time (seconds): 34.7448 (Failed: 0; 0%)
 Linear solve setup time (seconds): 0.817739 (Failed: 0; 0%)
 Update time (seconds):       1.19936 (Failed: 0; 0%)
 Output write time (seconds): 2.05066
Overall Well Iterations:      0 (Failed: 0; -nan%)
Overall Linearizations:       737 (Failed: 0; 0%)
Overall Newton Iterations:    599 (Failed: 0; 0%)
Overall Linear Iterations:    14314 (Failed: 0; 0%)
```

**Comment by moyner** [comment]
If I disable `UNIFOUT` the behavior seems in line with what you observe. Then this may be fixed on master and may not be related to the use of WSL2.

> Number of MPI processors:      1
> Threads per MPI processor:     2
> Total time (seconds):         36.0716
> Solver time (seconds):        35.8289
>  Assembly time (seconds):     10.3622 (Failed: 0; 0%)
>  Linear solve time (seconds): 21.2526 (Failed: 0; 0%)
>  Linear solve setup time (seconds): 0.535149 (Failed: 0; 0%)
>  Update time (seconds):       1.01035 (Failed: 0; 0%)
>  Output write time (seconds): 1.88334
> Overall Well Iterations:      0 (Failed: 0; -nan%)
> Overall Linearizations:       608 (Failed: 0; 0%)
> Overall Newton Iterations:    472 (Failed: 0; 0%)
> Overall Linear Iterations:    9559 (Failed: 0; 0%)

**Comment by bska** [comment]
> If I disable `UNIFOUT` the behavior seems in line with what you observe. Then this may be fixed on master and may not be related to the use of WSL2.

Very good; then maybe we'll leave this as is for now.  If the problem persists in 2020.04, then we'll obviously need to reconsider.  I'll nevertheless take note of the apparent increase in solver iterations  and see if I can reproduce that locally.

In any case, thank you very much for the report!

**Comment by moyner** [comment]
Thank you - I will reopen this if the write time isn't fixed by the upcoming release.
