### ISSUE TITLE
Unable to compile and build OPM Simulator in macOS Catalina unknown ParallelISTLInformation

### ISSUE THREAD

**Issue by binpetro** [OPM/opm-simulators#2657]
While compiling the OPM-Simulator, I keep getting the error message
```
"opm-simulators/opm/simulators/flow/countGlobalCells.hpp:115:23: error: unknown type name 'ParallelISTLInformation'
```
All the DUNE and other pre-requisites are compiled and present. Not sure why this keeps coming back.

**Comment by bska** [comment]
Hi,

The most obvious cause of that error would be that the [condition](https://github.com/OPM/opm-simulators/blob/04f6c240220ab4c9e7b7eca9eb0bd5a84ef898b9/opm/simulators/linalg/ParallelIstlInformation.hpp#L37)
```C++
#if HAVE_MPI && HAVE_DUNE_ISTL
```
is `false`.  That would cause the `ParallelISTLInformation` type to not exist at all.  Since the error occurs on a [line](https://github.com/OPM/opm-simulators/blob/04f6c240220ab4c9e7b7eca9eb0bd5a84ef898b9/opm/simulators/flow/countGlobalCells.hpp#L115) that requires `HAVE_MPI` to be `true` I would first check if `HAVE_DUNE_ISTL` is `false` for some reason.

Would you be able to provide a more complete backtrace of the compile failure?  My initial suspicion is that there's some top-level `.cpp` file that does not include `config.h` and that we somehow get away with this on GCC.

**Comment by binpetro** [comment]
Based on my traceback, the argument is in op-simulators/opm/simulators/finalg/ParallelIstlInformation.hpp. Its while compiling flow files. 
Perhaps its looking for Dune-istl directory. I tried to supply it with CMAKE_FLAGS, but seems to be ignoring. Not sure why.. any suggestion.

**Comment by blattms** [comment]
Did you follow the instructions for MacOS at https://opm-project.org/?page_id=239 (last section) and then the general build instructions at https://opm-project.org/?page_id=231?

In that case please post the output of `make VERBOSE=1` in the build directory of opm-simulators,
In addition the CMakeCache.txt file there and the config.h are of interest.

**Comment by binpetro** [comment]
Hi, 
Indeed, I was following the same direction as given in OPM install website for MacOS. I am using the newer version of OS. As suggested please find the file. 
[CMakeCache.txt](https://github.com/OPM/opm-simulators/files/4745516/CMakeCache.txt)
[output.log](https://github.com/OPM/opm-simulators/files/4745519/output.log)
[CMakeOutput.log](https://github.com/OPM/opm-simulators/files/4745521/CMakeOutput.log)
[CMakeError.log](https://github.com/OPM/opm-simulators/files/4745522/CMakeError.log)
[config_h.txt](https://github.com/OPM/opm-simulators/files/4745532/config_h.txt)
I have to add a .txt extension to config.h file as I was unable to upload it. 
Please check and suggest what I have missed or what needs to be done.

**Comment by bska** [comment]
Your `config.h` has the following line
```C++
/* #undef HAVE_DUNE_ISTL */
```
which means that `HAVE_DUNE_ISTL` evaluates to `false`.  That is along the lines of what I suspected earlier and it means that, for whatever reason, OPM's configure checks were unable to locate Dune ISTL.

**Comment by bska** [comment]
I **think** there's a clue in `CMakeError.log`.  When checking for Dune ISTL, the compiler is invoked as
```
/path/to/c++  \
    -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 \
    -DENABLE_TBB=1 \
    -DHAVE_BOOST=1 \
    -DHAVE_MPI=1 \
    -DHAVE_PARMETIS=1 \
    -DMPI_2=1 \
    -D_TBB_CPP0X \
    -I/path/to/dune-istl \
    -I/path/to/dune-common \
    -I/usr/local/Cellar/open-mpi/4.0.3/include \
    -isystem /usr/local/include  \
    -DHAVE_DUNE_ISTL \
    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk \
    -o CMakeFiles/cmTC_1d851.dir/src.cxx.o \
    -c /path/to/CMakeFiles/CMakeTmp/src.cxx
```
and there's no sign of a flag to request a language version.  Since you're on macOS I assume that you're using Clang and if there's no language version that probably defaults to C++11 (maybe even C++98 or C++03).  In any case, the check for Dune ISTL tries to compile code that uses C++17 and if the compiler is not in C++17 mode the code fails to compile and the configure system therefore assumes that Dune ISTL is unavailable which leads to the symptoms you're seeing.

I'm not sufficiently familiar with macOS to suggest a remedy here.  My colleague @atgeirr uses macOS and may have additional input.

**Comment by atgeirr** [comment]
Maybe the "detect c++17 and set appropriate flags" part of the build system does not work with clang (or on mac)? I see that I do this
```
set(CMAKE_CXX_FLAGS "-std=c++17" CACHE STRING "Compiler flags")
```
(and more, but that is the only important part), in my cmake cache file, that I invoke by passing `-C filename` to cmake. Perhaps that hid a building problem for me?

As a workaround in the meantime, try doing the same (in a clean build dir) and see if it works!

**Comment by binpetro** [comment]
Thanks everyone for active participation. The work around suggested by atgeirr worked well. 

atgeirr: I was wondering if you would like to share the cmake flags that you normally use for OPM compilation. I am facing another issue in compiling OPM-Upscaling routine. 

Thanks any way. This should close this issue

**Comment by atgeirr** [comment]
Here is my "releaseopts.cmake" file. There are probably things here that could be removed, or are better done in other ways, but the basic stuff here has stayed with me for half a decade or so, so I do not change it unless I have to. I have a "debugopts.cmake" file as well for convenience, the only difference is that it sets CMAKE_BUILD_TYPE to "Debug".
```
set(PRECOMPILE_HEADERS OFF CACHE BOOL "Precompiled headers")
set(SILENCE_EXTERNAL_WARNINGS ON CACHE BOOL "Silence warnings from external libraries")
set(SILENCE_CROSSMODULE_WARNINGS ON CACHE BOOL "Silence warnings from other modules")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "Export commands for analysis tools")
set(USE_MPI ON CACHE BOOL "Use MPI")
set(USE_OPENMP OFF CACHE BOOL "Do not use OpenMP")
set(USE_PTHREAD OFF CACHE BOOL "Do not use pthreads")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type")
set (CMAKE_CXX_FLAGS
        "-pipe -std=c++17 -pedantic -Wall -Wextra -Wformat-nonliteral -Wcast-align -Wpointer-arith -Wmissing-declarations -Wcast-qual -Wshadow -Wwrite-strings -Wchar-subscripts -Wredundant-decls -Wno-unused-local-typedef -Wno-keyword-macro -Wno-missing-braces -Wno-gnu-zero-variadic-macro-arguments -Wno-format-nonliteral -Wno-cast-align"
        CACHE STRING "Flags used by the compiler during all build types")
set (CMAKE_C_FLAGS_DEBUG
        "-O0 -g"
        CACHE STRING "Flags used during Debug builds")
set (CMAKE_CXX_FLAGS_DEBUG
        "-O0 -g"
        CACHE STRING "Flags used during Debug builds")
set (CMAKE_C_FLAGS_RELEASE
        "-O2 -DNDEBUG -march=native -mtune=native"
        CACHE STRING "Flags used during Release builds")
set (CMAKE_CXX_FLAGS_RELEASE
        "-O2 -DNDEBUG -march=native -mtune=native"
        CACHE STRING "Flags used during Release builds")
```
