### ISSUE TITLE
[MPI] error message is not printed when parser fails if HAVE_MPI is true

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#2764]
I have a deck that abort without any error message due to line 254 in readDeck.cpp

`MPI_Abort(MPI_COMM_WORLD, EXIT_FAILURE);`

In debug mode I can read the failureMessage and it points to the real issue in the deck, but the failureMessage is not printed in the terminal. 

Another way to provoke an error without a failure message is to try to run flow with a deck that doesn't exist. It will abort but not tell you why.

**Comment by blattms** [comment]
Without any deck I get the error message printed (with rubbish about MPI_Abort, though).

Unfortunately, I have no deck where the program fails like your test. Can you provide one?

BTW if we end up in [readDeck.cpp:253](/OPM/opm-simulators/blob/09412bea6267cde17d684c41b8ffeef1d8e559ff/opm/simulators/utils/readDeck.cpp#L253), Then the parsing has failed and that should have written an error message out, which because of the syncronization during the call `parseSuccess = comm.max(parseSuccess)` (global communication) should haven been written by now.

One could of course throw an exception instead of aborting here, which might remove the messages about the abort that obfuscate things.

**Comment by blattms** [comment]
Turns out, that I have one such deck.
