### ISSUE TITLE
[Ubuntu,rc2] Packages should use libptscotchparmetis

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2883]
I did take a look at the ubuntu packages and it seems like they are not linked to libptscotchparmetis. That even though the fix OPM/opm-common#2061 is in people will not get the full scalability of AMG (not sure whether that is an issue as there might still be bugs, see https://opm-project.org/pipermail/opm/2020-October/000698.html.

BTW The Ubuntu packages of dune-istl seem to not even recommend ptscotch or parmetis. I will try to sort this out upstream.

**Comment by atgeirr** [comment]
I did a test in a clean VM with what I believe was rc2 (even though --version said it was rc1), and is still reports that "Successive accumulation of data on coarse levels only works with ParMETIS installed.  Fell back to accumulation to one domain on coarsest level". So that is consistent with this observation.

**Comment by bska** [comment]
> though `--version` said it was rc1

Yes, sorry about that.  I failed to update the `dune.module` file when tagging RC-2.  This is fixed in the upcoming RC-3 tag.  Package builds for that tag is being scheduled today.

> "Successive accumulation of data on coarse levels only works with ParMETIS installed. Fell back to accumulation to one domain on coarsest level". So that is consistent with this observation.

The package master tells me that the RC-3 packages will address this issue.
