### ISSUE TITLE
Support GRIDOPTS option TRANMULT=YES

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#3435]
Right now, setting TRANMULT to YES will give an unsupported feature warning in Flow, and the option is ignored.

**Comment by OPMUSER** [comment]
Yes, that's because I have this in the manual:

![image](https://user-images.githubusercontent.com/17958927/124732388-bce82500-df45-11eb-802f-e937e9e3632c.png)

If it is incorrect then it is easy to change and to update the manual.

All the PartiallySupportedKeyword checking will generally continue, even if the message says "will STOP". I'm in the process of re-submitting the PartiallySupportedKeyword based on alphabetic order, rather than by section, as I think this will be easier to review and check. I expect there will be quite a bit of feedback to these changes.

All the keywords are done as a first pass and the first batch (A-E) should be submitted today with a bit of luck.
