### ISSUE TITLE
2021-04 MPI Bug in Release?

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#3510]
When I run SPE01 in sequential model I get this in terms of timing:
```
Number of MPI processes:         1
Threads per MPI process:         2
Total time (seconds):           17.27 
Solver time (seconds):          16.90 
 Assembly time (seconds):        0.92 (Failed: 0.0; 0.0%)
   Well assembly (seconds):      0.15 (Failed: 0.0; 0.0%)
 Linear solve time (seconds):    0.25 (Failed: 0.0; 0.0%)
   Linear setup (seconds):       0.06 (Failed: 0.0; 0.0%)
 Update time (seconds):          0.74 (Failed: 0.0; 0.0%)
 Pre/post step (seconds):        0.79 (Failed: 0.0; 0.0%)
 Output write time (seconds):   14.23
Overall Linearizations:        454    (Failed:   0; 0.0%)
Overall Newton Iterations:     329    (Failed:   0; 0.0%)
Overall Linear Iterations:    2744    (Failed:   0; 0.0%)
```
When I run in parallel with mpi np=2 get:
```
Number of MPI processes:         2
Threads per MPI process:         1
Total time (seconds):           20.77 
Solver time (seconds):          20.34 
 Assembly time (seconds):        0.49 (Failed: 0.0; 0.0%)
   Well assembly (seconds):      0.20 (Failed: 0.0; 0.0%)
 Linear solve time (seconds):    0.31 (Failed: 0.0; 0.0%)
   Linear setup (seconds):       0.03 (Failed: 0.0; 0.0%)
 Update time (seconds):          0.23 (Failed: 0.0; 0.0%)
 Pre/post step (seconds):        0.71 (Failed: 0.0; 0.0%)
 Output write time (seconds):   18.75
Overall Linearizations:        446    (Failed:   0; 0.0%)
Overall Newton Iterations:     322    (Failed:   0; 0.0%)
Overall Linear Iterations:    2872    (Failed:   0; 0.0%)
```
I'm running in a VM.

Notice that in the sequential run I have 1 process x 2 threads = 2 and in the parallel run I have 2 processes x 1 thread = 2, which is perhaps why the run times are similar.

Comments?

**Comment by blattms** [comment]
Not sure whether this is a bug. The problem is really small. On my system using 2 OPM threads  and 4 MPI processes is slower than 4 MPI processes with 1 OPM thread.

What strikes me, is that the assembly on your system already takes 4 times the time for 2 MPI processes. How many procs does the virtual machine report (tail -n 20 /proc/cpuinfo). Maybe we are already oversubscribing? (I see a a factor 80 slower if I use 8 MPI processes with 2 OMP threads on my 8-core machine).

Anyway the problem is really small and generally I would not expect much anyway from going parallel.

**Comment by atgeirr** [comment]
I notice that these times are dominated by output write time (and are very long for SPE1 runs, do not know why), not sure if that was what you thought was the bug? The comments of @blattms stand, regarding other timings observed.

**Comment by OPMUSER** [comment]
@atgeirr not originally. The issue was that performance did not improve with more threads, but as @blattms pointed out that was due to the problem being small. So I ran the Norne model as a benchmark.

Running under WSL I have this configuration

```
david@EIPC-02:~$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Stepping:            3
CPU MHz:             2712.000
CPU max MHz:         2712.0000
BogoMIPS:            5424.00
Virtualization:      VT-x
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container
```

Sequential run

```
Number of MPI processes:         1
Threads per MPI process:         2
Total time (seconds):          523.75
Solver time (seconds):         522.86
 Assembly time (seconds):      126.62 (Failed: 1.4; 1.1%)
   Well assembly (seconds):      4.19 (Failed: 0.0; 1.2%)
 Linear solve time (seconds):  277.34 (Failed: 2.1; 0.8%)
   Linear setup (seconds):      29.08 (Failed: 0.4; 1.4%)
 Update time (seconds):         63.47 (Failed: 0.9; 1.3%)
 Pre/post step (seconds):       44.34 (Failed: 0.1; 0.1%)
 Output write time (seconds):    8.50
Overall Linearizations:       1887    (Failed:  21; 1.1%)
Overall Newton Iterations:    1517    (Failed:  21; 1.4%)
Overall Linear Iterations:   23304    (Failed: 148; 0.6%)
```
Parallel run with np=2

```
Number of MPI processes:         2
Threads per MPI process:         2
Total time (seconds):          365.69
Solver time (seconds):         364.70
 Assembly time (seconds):       90.86 (Failed: 0.0; 0.0%)
   Well assembly (seconds):      7.84 (Failed: 0.0; 0.0%)
 Linear solve time (seconds):  188.75 (Failed: 0.0; 0.0%)
   Linear setup (seconds):      20.86 (Failed: 0.0; 0.0%)
 Update time (seconds):         38.57 (Failed: 0.0; 0.0%)
 Pre/post step (seconds):       37.32 (Failed: 0.0; 0.0%)
 Output write time (seconds):    7.27
Overall Linearizations:       1825    (Failed:   0; 0.0%)
Overall Newton Iterations:    1465    (Failed:   0; 0.0%)
Overall Linear Iterations:   22717    (Failed:   0; 0.0%)

```
Parallel run with np=4

```
Number of MPI processes:         4
Threads per MPI process:         2
Total time (seconds):          338.62
Solver time (seconds):         337.41
 Assembly time (seconds):       76.83 (Failed: 0.0; 0.1%)
   Well assembly (seconds):     10.89 (Failed: 0.0; 0.1%)
 Linear solve time (seconds):  182.36 (Failed: 1.4; 0.8%)
   Linear setup (seconds):      20.17 (Failed: 0.0; 0.1%)
 Update time (seconds):         31.78 (Failed: 0.0; 0.0%)
 Pre/post step (seconds):       37.58 (Failed: 0.0; 0.1%)
 Output write time (seconds):    7.29
Overall Linearizations:       1820    (Failed:   1; 0.1%)
Overall Newton Iterations:    1455    (Failed:   1; 0.1%)
Overall Linear Iterations:   22721    (Failed: 200; 0.9%)

```
Parallel run with np=6  

```
There are not enough slots available in the system to satisfy the 6
slots that were requested by the application:
```
Which is correct as there is only four cores. However, under WSL Python picks up the number of threads, whereas on Linux it picks up the number of cores, which adds to the confusion as I use OPMRUN to run all my jobs.

Thus for Norne model, performance improves the more resources we give the simulator - so all good.

This conversation was started as a friend stated that OPM Flow was 50% slower than the commercial simulator, which it is for small jobs from the results he sent.

So it would be good to see some benchmarks against the commercial simulator to see if we have performance issues on small or large models. At the moment we benchmark ourselves frequently, but it would be good to use the same benchmarks using the commercial simulator. Perhaps we should do this one month before a scheduled release so we can rectify any regressions.

What do you think?

**Comment by atgeirr** [comment]
> So it would be good to see some benchmarks against the commercial simulator to see if we have performance issues on small or large models. At the moment we benchmark ourselves frequently, but it would be good to use the same benchmarks using the commercial simulator. Perhaps we should do this one month before a scheduled release so we can rectify any regressions.
> 
> What do you think?

This would need to be done by someone with access to proprietary simulators, and could be worth doing if automated, but I do not think it adds much value to what we are already doing with linuxbenchmarking.com (although that seems to be down today?) except to take into account improvements made in the commercial sims over time. Paying the benchmarkers to benchmark a proprietary sim including providing them the necessary licenses would be a large expense (esp. the licenses!).

The issue itself is resolved I think. Close it?

**Comment by alfbr** [comment]
> Running under WSL I have this configuration

For general benchmark purposes, I do not think WSL is a good choice. It introduces a number of uncertainty factors that are beyond what we can control in Flow. Unless there is something specific in Flow that degrades performance on WSL. Also keep in mind that laptops are also prone to noisy benchmarks (due to autmatic re-clocking of CPUs and bad cooling). For number of cores to make sense, you also need to know if hyperthreading is active. There is no sense in issuing as many processes to MPI as there are threads available on a CPU with hyperthreading active.

> So it would be good to see some benchmarks against the commercial simulator

We are doing this on all models we are working with, as I believe any other energy company would. On the Norne model in particular, there is  publication coming. It is a one time off thing though, there is little sense in testing performance on the same model multiple times with commercial simulators unless they have changed (typically a new release). Hence, I do agree with @atgeirr , I see no value in setting up regular benchmarks for commercial simulators.

**Comment by OPMUSER** [comment]
@alfbr and @alfbr to be clear, I'm not suggesting that we run the commercial simulator multiple times, but that we have a comparison between the two for all the developers to see.

I'll close this as @alfbr does this internally, but it would be nice to share the results for models x,y, and z. :-)

**Comment by alfbr** [comment]
> I'll close this as @alfbr does this internally, but it would be nice to share the results for models x,y, and z. :-)

Sure, just ask :-) On proprietary data sets, it is difficult to share results, but we are working on a publication for that also on large data sets. For Norne, Flow is faster than both Eclipse and Intersect on all CPU counts. Among the SPE data sets, I guess 9 is the only one we have done benchmarking on, since 10 is still immature and the others too small. Current status on SPE9_CP.DATA on a slow workstation here is 11.01 seconds for Eclipse and 28.95 seconds for Flow. Generally speaking, Eclipse with nested factorization does well on small models. On larger models, the picture changes, but it really depends on the model. Yes, we would still love to have nested factorization in the Flow toolbox ;-)

**Comment by bska** [comment]
> For general benchmark purposes, I do not think WSL is a good choice. It introduces a number of uncertainty factors that are beyond what we can control in Flow.

Especially if we're talking about WSL rather than WSL2.

> For number of cores to make sense, you also need to know if hyperthreading is active. There is no sense in issuing as many processes to MPI as there are threads available on a CPU with hyperthreading active.

True.  Recent versions of OpenMPI, in particular, will in their default configuration refuse to run a job if the number of MPI processes exceeds the number of physical cores in the system.  There are ways to reconfigure OpenMPI to lift that restriction, but they're typically not useful when running on laptops.

**Comment by atgeirr** [comment]
> There are ways to reconfigure OpenMPI to lift that restriction, but they're typically not useful when running on laptops.

I do that to stress test our MPI implementation sometimes. Useful to verify that things actually can run with 97 processes... But the performance is then of course not useful.
