### ISSUE TITLE
OPM-Simulator release on hirsute?

### ISSUE THREAD

**Issue by Tunneller** [OPM/opm-simulators#3544]
The testing ppa for opm is at https://launchpad.net/~opm/+archive/ubuntu/testing

It has *almost* everything needed for a binary hirsute build, but there is a note that opm-simulators failed to build [20 weeks ago] and nothing since then. What is the status? Is this something that we could help on??

Has anyone succeeded in building OPM on hirsute??

Thanks, Tunneller

**Comment by akva2** [comment]
my memory is a little faint, but i believe it triggered some generic gcc10 issues that i have since addressed. that said the testing ppa is not for end users, it is only something in use during release phases to avoid messing up the main one with release candidates. only lts versions receive actual release builds from us.

**Comment by Tunneller** [comment]
Ok thanks, I will use the 20.04 build. I'm excited to get started on OPM :-)
