### ISSUE TITLE
Unexpected file written out by default

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#3710]
Flow by default prints out a file with suffix INFOSTEP. This file seems to be only for developers of numerical optimizations that want additional information. For users the file is noise, and scripts to clean up folders after simulations may need to be aware of it. There are at least three options that could remedy this, and I believe all of them is better:
* make the output of the file optional, for instance through a command line switch
* add the extra time step information to the LOG and/or PRT file
* send the information to the DBG file, for instance starting each line with the string INFOSTEP to make it trivial to extract

**Comment by blattms** [comment]
Wow, this files has a long renaming history:
.ITERINFO -> STEPINFO ->INFOSTEP

Seems like the functionality was added in 769028b by @atgeirr. Maybe he should share his views.

**Comment by atgeirr** [comment]
I find the file very useful, and it is important to keep the information. Having it in a separate file as is done now is the most straightforward and reasonable way in my opinion. According to @alfbr user consider that the file is useless noise, and I will not challenge that, but I find it a little puzzling. That cleanup scripts need to be aware of it is a real issue, which stems from the weird way of approaching output in Eclipse (not by default putting the results in a separate directory). I am fine with putting it in the PRT or LOG file instead. Although I had the impression that what went into the PRT file was very particular, and not to be tampered (much) with? Same with LOG, we do not even write one, which is because it "should be like Eclipse" if we do it. Is that no longer a concern? Adding it to the DBG file may of course also be done.

**Comment by blattms** [comment]
@OPMUSER did propose this in OPM-OP a while ago:
"Currently OPM Flow outputs numerical performance data to the *.INFOSTEP file which is a OPM Flow specific  output file. This data should be in the *.DEBUG file and output should be controlled by the RPTDEBUG keyword. Secondly, some of the variables map to SUMMARY variable and perhaps all the variables in this report should also be reported in the SUMMARY file."
