### ISSUE TITLE
FAILED to LAUNCH the model with polymer flooding

### ISSUE THREAD

**Issue by DanatKMGE** [OPM/opm-simulators#3791]
Good day! I tried to use the simulator to calculate the model with polymer flooding. But it failed to launch. The stepsize is constantly divisible by 3 and it reaches the minimum limit. If you remove the POLYMER from the .DATA file, then everything starts fine. 

I am attaching the .DATA and .DBG files below:
[RES.zip](https://github.com/OPM/opm-simulators/files/7949291/RES.zip)

**Comment by blattms** [comment]
Thanks for the report and data set. Not sure how well polymer flooding is tested as there is at least #3386 in addition.

Judging from you description the (non-)linear solver might have serious convergence and the time steps are copped.

**Comment by GitPaean** [comment]
Hi, @DanatKMGE ,

Sorry for the late response and thanks for providing the DATA file. 

In your DATA file, the following keywords is provided, 
```
 PLYADS
   0.0  0.005
   50.0  0.010 /
```

This is the reason why the simulation can not get converged because it is physically impossible.  With zero polymer concentration, it is impossible have some polymer adsorbed by the rock formation. 

If you change the keyword as follows, 

```
 PLYADS
   0.0  0.00
   50.0  0.010 /
``` 
The simulation will run. 

Hope it is helpful to you. 

If this issue is fixed to you, feel free to close this issue.  If you have more comments, please let us know.

**Comment by DanatKMGE** [comment]
Thank you very much! The simulator is up and running! I realized my mistake.
