### ISSUE TITLE
Running multiple models with mpirun -np 2 

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#3825]
When running multiple flow instances with mpirun -np 2 on our cluster with 72X2 cores results in only 2 processes being used. If for instance N instances are run (typical setting for ensemble runs). The %CPU as shown in `top` goes down to 200%/N for each of the instances. This is independent on N. e.g. it happens for N=2, N=3 etc. For -np 3 everything works fine. e.g. the %CPU stays the same independently of number of instances as long as N < 72. 

Any clue why this happens? Is this a local issue with our hardware or can this be reproduced in other settings?

**Comment by blattms** [comment]
I am a bit surprised. Shouldn't the queueing system of the cluster make sure that CPUs are reserved and mpirun only uses those? Or are you starting multiple runs in one batch script or without a queueing system?

I would advise to talk to cluster administrator on how to do this.

Doing this manually is quite tedious, because  if this OpenMPI then the default way to bind processes is (See [man-page](https://www.open-mpi.org/doc/current/man1/mpirun.1.php)):
- For 2 or less processes: bind to core
- For more: bind to socket

The behavior of course depends on the hardware (how many cores per socket). Obviously, the first falls on your feet. Why the second one is not a problem for you, is not 100% clear to me (maybe enough cores per socket and the OS does the right thing).
MPI itself will not check which core is idle.

You can specify the set of cpus to use with [--cpu-set](https://www-lb.open-mpi.org/faq/?category=openfabrics#cpu-set), use [numactl,](https://stackoverflow.com/questions/30215729/openmpi-and-rank-core-bindings) rely on the operating system using --bind-to-none,

**Comment by blattms** [comment]
BTW you could to use the `--report-bindings` options to see where the tasks end up.
