### ISSUE TITLE
About new release

### ISSUE THREAD

**Issue by User22814** [OPM/opm-simulators#3856]
Good day to all! I would like to ask about the new release. When will it be and what will be new? Will there be an alkaline flood?

**Comment by blattms** [comment]
As always we will release in April and October each year, Hence you can expect a release at the end of this month or early May. It will usually include all the features that were in the master branch right now. You can see for yourself by looking at the PRs, e.g. [opm-simulator PRs merged since 2021-10](https://github.com/OPM/opm-simulators/pulls?q=is%3Apr+is%3Amerged+created%3Aopen%3E2021-10-01).

I'll leave the last (alkaline) question to others.

**Comment by blattms** [comment]
I am closing this, please refer to #3860 for updates about the release.
