### ISSUE TITLE
Issue with repeated rv's in PVTG

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#3881]
Issue first mentioned in #3850

The issue is related to the "erase" part. Why bother with removing duplications? Is the purpose speedup?  Removing line 728 is sufficient for the simulator to work. 

https://github.com/OPM/opm-material/blob/2cf4986b72a42ae5af0a8b9256520db96e0addc6/opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp#L728

**Comment by bska** [comment]
> Why bother with removing duplications? Is the purpose speedup?

As far as I can tell we prune duplicate Rv values in order to create an invertible `RvSat(p)` curve which, in turn, is used to [compute the `PBUB` solution vector](https://github.com/OPM/opm-simulators/blob/14866907384659cac8a239e855e6e16b4ed70555/ebos/ecloutputblackoilmodule.hh#L401).  The call to [`FluidSystem::bubblePointPressure()`](https://github.com/OPM/opm-material/blob/2cf4986b72a42ae5af0a8b9256520db96e0addc6/opm/material/fluidsystems/BlackOilFluidSystem.hpp#L1222) ends up in [`WetGasPvt<>::saturationPressure()`](https://github.com/OPM/opm-material/blob/2cf4986b72a42ae5af0a8b9256520db96e0addc6/opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp#L590) and that function requires an invertible `RvSat(p)` curve.

I'm not saying this is a good reason.

**Comment by totto82** [comment]
I see. A simple solution could be to only "erase" if number of unique points are more than 1. The newton solve returns psat if the derivative is zero. I guess that is the best you can do if the rv's are constant.
