### ISSUE TITLE
custom library search path in installed simulators.cpython-310-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#4221]
linitan for Debian spits out an error for this:
```
E: python3-opm-simulators: custom-library-search-path RUNPATH /usr/lib/x86_64-linux-gnu/openmpi/lib [usr/lib/python3/dist-packages/opm/simulators/simulators.cpython-310-x86_64-linux-gnu.so]
```
Need to find out how to solve this. Usually these search paths should be set outside for installed package, I guess.
@hakonhagland Do you happen to know whether we changed any of these search paths after the last release?

**Comment by hakonhagland** [comment]
Hi @blattms, I am not familiar with Lintian or debian packaging. Found some information about the error message here: https://lintian.debian.org/tags/custom-library-search-path. From that information, the error happens because the rpath `/usr/lib/x86_64-linux-gnu/openmpi/lib` is included in the shared library `simulators.cpython-310-x86_64-linux-gnu.so` ?

**Comment by blattms** [comment]
Thsnks. Sorry for not being clear. My question was whether we changed the build system to include these and why?

**Comment by blattms** [comment]
I have solved this in the debian packages via setting `SKIP_BUILD_RPATH` to `TRUE`. Not sure whether we need the fix here. Closing
