### ISSUE TITLE
Defaulted reference depth of well in aquifer grid block 

### ISSUE THREAD

**Issue by steink** [OPM/opm-simulators#4222]
When a grid block contains both a numerical aquifer (AQUNUM) and a well, the depth set by AQUNUM is not used when defaulting the well referende depth (rather the grid block geometric depth is used).

**Comment by OPMUSER** [comment]
Well if I understand @steink description of the issue correctly, this not a bug in terms of reference depth.

One should not have wells in numeric aquifer blocks period; secondly, the numeric aquifer cells should be completely isolated from the reservoir, and that all connections should only be explicitly defined via the `AQUCON` keyword (we don't support the AQUNNC keyword).

So the bug is that we allowed this to occur. To be clear, there should be no wells in numeric aquifer blocks.

It would be good to check for this, as well as for any "natural" numeric aquifer cells connecting to active reservoir cells.

**Comment by GitPaean** [comment]
> One should not have wells in numeric aquifer blocks period; 

Why do you think so, is there some reference or argument regarding this?


> secondly, the numeric aquifer cells should be completely isolated from the reservoir, and that all connections should only be explicitly defined via the AQUCON keyword

Yes, in this targeting case, these numerical aquifer cells (that have wells specified with them) do not have connection with AQUCON, so they are isolated first, then they connect these cells connect to another aquifer cell, which is connected to the rest of the reservoir. 

> So the bug is that we allowed this to occur. 

Partly agree. But the commercial simulator looks having no problem with it.

**Comment by OPMUSER** [comment]
@GitPaean 

> Why do you think so, is there some reference or argument regarding this?

Because the well results are garbage, I had assume this was modelling water disposal into the aquifer, in my initial comment.

> Partly agree. But the commercial simulator looks having no problem with it.

Just because commercial simulator allows it does not mean it is physically or mathematically correct. At the very least there should be warning messages regarding this, so the user is aware that this is a potential issue.

@vkip 

> Wells in numerical aquifers are sometimes used as source terms, to model the effect of outtake in nearby connected reservoirs. In this case the well pressure is usually not important, but it makes sense to also update the well reference depth, I think.

Well if you are doing this then the well model is completely wrong, so I don't understand the concern of the well reference depth. Why not just adjust the aquifer properties. Nevertheless, I can see this is an easy fix for when multiple reservoirs with different withdrawal rates are connected through a common aquifer.

**Comment by steink** [comment]
I agree that the bhp of these special wells are not really relevant/interesting quanties, but I don't think it's unlikely that having a reference depth far off that set in AQUNUM could lead to undesired issues. 

Maybe related, for aquifer grid blocks, properties PORO and PORV written to init-file agree with that set in AQUNUM, while the DEPTH-property is just the grid block z (and not the DEPTH set in AQUNUM).

**Comment by GitPaean** [comment]
>  while the DEPTH-property is just the grid block z (and not the DEPTH set in AQUNUM).

Okay. Then this is another fallout need to be fixed.
