### ISSUE TITLE
Transient Well Test

### ISSUE THREAD

**Issue by lucianounicamp** [OPM/opm-simulators#4577]
Hi, is OPM able to deal with transient well test simulation? If yes, what's the best way to prepare/configure the model to get reliable results?

Regards

Luciano

**Comment by goncalvesmachadoc** [comment]
Hello Luciano,

Although reservoir simulators are not ideal for well testing modelling, you could use opm-flow for it in the same way you would use other reservoir simulators. If what you have in mind is a typical old-school setup, I would recommend using the SPIDER grid with tiny grids around the well, increasing exponentially towards the reservoir boundary.  Also tiny time steps increasing exponentially after each rate change. How to set  the boundaries depends on what you are trying to achieve. We can discuss it further if you whish, and maybe prepare a case for opm-tests?

Cheers,

**Comment by goncalvesmachadoc** [comment]
Hi Luciano.

The local grid refinement (LGR) feature is still under development at the moment. So for now, you won't be able to do that in a straightforward way. In addition, allowing for local time stepping I believe is not our priority in the LGR developments for this year. Anyway, if you are looking into well testing modelling in scale of days, refining the time stepping globally should not be so bad? My google email account is cintiamachadorc at gmail.

Best,

**Comment by OPMUSER** [comment]
@lucianounicamp Just it add to @goncalvesmachadoc comments, more from an RE prospective.

The simulator does not care about the flow regime, transient, pseudo-steady state, steady state etc. It is the time step size that determines how one captures the flow regime. So yes, OPM Flow can model the various flow regimes.

If you are trying to match a DST well test then you need to use ether a radial grid or a  SPIDER grid. The inner radius should be the wellbore radius and then this should expand on a log scale to the outer radius. You need to model both the flow period and the buildup period. To capture the transient behavior, I typically use three to five minute time steps. Note, all simulators struggle with this type of problem because all the inner cells have very small pore volumes compared to the fluid volume moving through them at each time step. See SPE02 Comparative Solution for an example.

Hopefully, the above is of some use.

**Comment by lucianounicamp** [comment]
@OPMUSER thank you, I'm sure your comments will help in the process. If I already have an upscaled model with conventional cartesian grid, do you think it's possible to generate a local SPYDER refinement? I'm working on UNISIM-1D benchmark and would like to simulate the transient responses of some wells

Regards

**Comment by OPMUSER** [comment]
@lucianounicamp unfortunately there is no way to generate a RADIAL/SPIDER LGR using OPM ResInsight.

However, you could manually create a  RADIAL/SPIDER grid based on the properties of the the host cells of the well in the global grid, using the standard radial keyword in OPM Flow.

**Comment by OPMUSER** [comment]
Closing a no response from @lucianounicamp after two weeks.
