### ISSUE TITLE
The capillary pressure values nan and nan are not finite

### ISSUE THREAD

**Issue by mbmfer** [OPM/opm-simulators#5000]
Hi,

I'm getting a “Program threw an exception: Could not initialize the problem: The capillary pressure values nan and nan are not finite” message. Does anyone have any idea about what may be causing this?. The SWOF and SGOF tables in this case use Pc=0. 
 
Kind regards and thanks a lot,
 
Mariano Fernandez

**Comment by bska** [comment]
Thank you for reaching out.

The message you're seeing is generated in exactly one place in OPM's source base and that code is invoked as part of initialising the simulation run&ndash;i.e., when computing the initial pressure and saturation distributions along with any initial dissolved gas/oil ratio ($R_s$) and/or vaporised oil/gas ratio ($R_v$). Since your model has $P_c = 0$ I **expect** that error is triggered as part of determining which kind of initialisation to run&ndash;i.e., whether or not there is a sharp interface between the phases at the gas/oil contact (free gas level) and/or oil/water contact (free oil level).

Does your model use saturation function end-point scaling?  If so that **might** be the direct trigger for the problem.  Our end-point scaling code for the capillary pressure curve does not appear to fully protect against division by zero and expressions like $0/0$ are the most common causes for `NaN` values.  The earlier work OPM/opm-material#481 tried to address this issue, but looks to have made the code somewhat more brittle.

If you are comfortable making changes to the C++ code and build the simulator from source I would suggest, as an experiment, to make the two changes below to the implementation files.  This adds a small positive value to the denominator in each expression which is a sledgehammer approach to avoiding division by zero.

---

```diff
diff --git a/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp b/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp
index 84a24c211..c3c0cfdac 100644
--- a/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp
+++ b/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp
@@ -487,7 +487,7 @@ private:
             if (scaled_maxPcnw == unscaled_maxPcnw)
                 alpha = 1.0;
             else
-                alpha = params.scaledPoints().maxPcnw()/params.unscaledPoints().maxPcnw();
+                alpha = params.scaledPoints().maxPcnw()/(params.unscaledPoints().maxPcnw() + 1.0e-5);
 
             return unscaledPcnw*alpha;
         }
@@ -510,7 +510,7 @@ private:
             if (scaled_maxPcnw == unscaled_maxPcnw)
                 alpha = 1.0;
             else
-                alpha = params.scaledPoints().maxPcnw()/params.unscaledPoints().maxPcnw();
+                alpha = params.scaledPoints().maxPcnw()/(params.unscaledPoints().maxPcnw() + 1.0e-5);
 
             return scaledPcnw/alpha;
         }
```

**Comment by mbmfer** [comment]
Thanks a lot Bard,

I don’t have a lot of C++ coding experience.

Do you think that adjusting the Pc curve to a small value (maybe decimals of psi) would serve as an alternative work around in this case?

Effectively this model is using end point scaling.

Kind regards and thanks again,

Mariano

Sent from my iPhone

On 16 Nov 2023, at 11:00 AM, Bård Skaflestad ***@***.***> wrote:

﻿

Thank you for reaching out.

The message you're seeing is generated in exactly one place in OPM's source base and that code is invoked as part of initialising the simulation run–i.e., when computing the initial pressure and saturation distributions along with any initial dissolved gas/oil ratio ($R_s$) and/or vaporised oil/gas ratio ($R_v$). Since your model has $P_c = 0$ I expect that error is triggered as part of determining which kind of initialisation to run–i.e., whether or not there is a sharp interface between the phases at the gas/oil contact (free gas level) and/or oil/water contact (free oil level).

Does your model use saturation function end-point scaling? If so that might be the direct trigger for the problem. Our end-point scaling code for the capillary pressure curve does not appear to fully protect against division by zero and expressions like $0/0$ are the most common causes for NaN values. The earlier work OPM/opm-material#481<https://github.com/OPM/opm-material/pull/481> tried to address this issue, but looks to have made the code somewhat more brittle.

If you are comfortable making changes to the C++ code and build the simulator from source I would suggest, as an experiment, to make the two changes below to the implementation files. This adds a small positive value to the denominator in each expression which is a sledgehammer approach to avoiding division by zero.

________________________________

diff --git a/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp b/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp
index 84a24c211..c3c0cfdac 100644
--- a/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp
+++ b/opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLaw.hpp
@@ -487,7 +487,7 @@ private:
             if (scaled_maxPcnw == unscaled_maxPcnw)
                 alpha = 1.0;
             else
-                alpha = params.scaledPoints().maxPcnw()/params.unscaledPoints().maxPcnw();
+                alpha = params.scaledPoints().maxPcnw()/(params.unscaledPoints().maxPcnw() + 1.0e-5);

             return unscaledPcnw*alpha;
         }
@@ -510,7 +510,7 @@ private:
             if (scaled_maxPcnw == unscaled_maxPcnw)
                 alpha = 1.0;
             else
-                alpha = params.scaledPoints().maxPcnw()/params.unscaledPoints().maxPcnw();
+                alpha = params.scaledPoints().maxPcnw()/(params.unscaledPoints().maxPcnw() + 1.0e-5);

             return scaledPcnw/alpha;
         }

**Comment by goncalvesmachadoc** [comment]
@mbmfer Would be possible to share the case?

**Comment by bska** [comment]
> don’t have a lot of C++ coding experience.

That is of course absolutely fine.  Users should obviously not need to have C++ programming experience in order to run the simulator.  I just asked in case you do have such experience.

> Do you think that adjusting the Pc curve to a small value (maybe decimals of psi) would serve as an alternative work around in this case?

It would at least be an interesting test, maybe just make the maximum Pc value be a (small) positive value and leave the other points unchanged at $P_c = 0$.  If making such a change to your simulation model is easy then I would very much like to know if it makes the crash go away and knowing the outcome of that test will anyway help guide any further investigation we might do.

> Effectively this model is using end point scaling.

Understood.  Then this is something worth drilling into in my opinion.

**Comment by mbmfer** [comment]
After reviewing the deck once again I realized there was an inconsistency in the SWL grid. AFter sorting this problem I can confirm that Flow CAN work with Pc=0. You can close this issue. Thanks a lot everyone for your support.

**Comment by bska** [comment]
> After sorting this problem I can confirm that Flow CAN work with $P_c=0$. You can close this issue.

Cool, thanks&ndash;I'll close this now.
