### ISSUE TITLE
CO2 dissolution in CO2STORE

### ISSUE THREAD

**Issue by flammmes** [OPM/opm-simulators#5189]
I have noticed that the dissolved CO2 in the water phase (FWCD) has a different profile between the flow and the opm compositional simulators. The profile in the compositional simulator seems to follow the profile of the commercial simulators. 

This can be seen in the FWCD plot below, where the light blue line represents the opm compositional simulator and the dark blue line OPM flow. 

![image](https://github.com/OPM/opm-simulators/assets/77570362/cdd60b3a-0150-44ba-8ea6-5632079890e4)

It seems as though flow models mainly convective dissolution and not "first contact" dissolution of CO2 in brine. Am i missuing keywords?

For the black oil model i have used DISGAS and DRSDTCON while for the compositional one i have used DISGASW. Initially water is completely free of gas in both cases as I have set the value of RSVD to 0 everywhere and ZMFVD to 1 for H20 in the compositional simulator.

**Comment by flammmes** [comment]
So by changing the DRSDTCON value from 0.04 to 10 I managed to match FWCD to both models. 

![image](https://github.com/OPM/opm-simulators/assets/77570362/ced6d355-ffaf-48da-9871-cd966bcc98b0)

However, I don't feel confident in changing the value this much because it is much higher than the recommended upper limit.

**Comment by totto82** [comment]
If you want to compare with a compositional simulator you should not use DRSDTCON at all. (or use a very large number) Standard compositional runs will assume the cell to be in phase-equilibrium. For large cells this may not be the case, that is when you need DRSDTCON.  If you want to compare and look at the effect of DRSDTCON you will need to compare with a fine-scale compositional simulation. Note however that we plan to upgrade the DRSDTCON functionality in OPM soon (before the 2024-04 release) in order to better model the long term effect of convective mixing.

**Comment by flammmes** [comment]
Ok thank you so much for the clarification. So from what I understand, in your Black oil model, you take into account this fact by introducing the upscaled convective dissolution which is a function of static and dynamic properties. The goal is for FWCD to have similar shape to what a fine grid compositional one would have. As you explain in your paper this phase equilibrium assumption  overestimates how much CO2 is actually dissolved unless the compositional is fine scaled. 

Thank you very much for your explanation.
