### ISSUE TITLE
Flow 2024.04 not installing ?

### ISSUE THREAD

**Issue by EdmundStephens** [OPM/opm-simulators#5672]
When I use the usual upgrading procedure, it seems that the newer version is not being picked up. 

>```sh
> $ sudo apt install libopm-simulators-bin
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libopm-simulators-bin is already the newest version **(2023.10-rfinal-1~focal).**
> 0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.
>```
Any ideas what is not set up correctly? I am using Windows 10 with WSL 2. 
> ```
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.6 LTS
> Release:        20.04
> Codename:       focal
>```

**Comment by akva2** [comment]
focal has been out of support for a year now so 2023.10 is the last version that will be provided. upgrade your distro.

**Comment by bska** [comment]
As @akva2 says in his inimitably terse style is that the OPM project does not provide binary 2024.04 packages for Ubuntu 20.04 LTS.  If you're able to get a more recent Ubuntu distribution into your WSL setup, then that is indeed the easiest way to resolve the matter.  Otherwise, you might have to build the simulator from source yourself.

That said, I do recommend getting a more recent Ubuntu distribution if at all possible, because that will prepare you for the upcoming 2024.10 release of OPM as well.

**Comment by EdmundStephens** [comment]
Thanks, I updated my Ubuntu (which takes some time!) and not have the 2024.04 version running. 

> sudo apt update && sudo apt full-upgrade
> sudo do-release-upgrade

Suggest you add a note to this effect in the release notes or install instructions ?

**Comment by bska** [comment]
> I updated my Ubuntu [...] and not have the 2024.04 version running.

Is "not" supposed to say "now" here, or does the simulator not work after upgrading Ubuntu?

**Comment by EdmundStephens** [comment]
Indeed, helpful auto correct strikes again.It’s working.👍🏻On 15 Oct 2024, at 10:53, Bård Skaflestad ***@***.***> wrote:﻿

I updated my Ubuntu [...] and not have the 2024.04 version running.

Is "not" supposed to say "now" here, or does the simulator not work after upgrading Ubuntu?
