### ISSUE TITLE
multiple output for input specificatins. 

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#572]
There are some repeated output for some input specifications now. The output of `output_dir` is not even consistent. 

```
output_dir not found. Using default value 'output'.
output_dir not found. Using default value 'output'.
output_dir not found. Using default value '.'.
```

```
deck_filename found at /, value is NORNE_ATW2013.DATA
deck_filename found at /, value is NORNE_ATW2013.DATA
```

```
output not found. Using default value 'true'.
output not found. Using default value 'true'.
output not found. Using default value 'true'.
```

**Comment by atgeirr** [comment]
Each request for an input parameter is independent, and therefore it is quite possible to use different defaults in different places. That can usually be fixed by unification of the input parameters, usually by asking for them at a higher level and passing a struct containing parameters to the lower level.

However, in the particular case of output_dir, there is a dilemma. On one hand, we do not want to clutter the data directory with files, therefore we traditionally use 'output' as our default output dir. This applies to the vtk and matlab format output as well as some other files. However for the eclipse binary output, we default to the current directory, it is claimed that is what would be expected by reservoir engineers. I have not been able to resolve this dilemma in a better way yet.

Apart from that, it should be possible to get rid of the repeated queries.
