### ISSUE TITLE
Add OPM_DATA to automated jenkins build?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#643]
Both opm-parser and opm-simulators can optionally run some integration tests based on the simulation decks found in opm-data:

opm-parser: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/IntegrationTests/CMakeLists.txt#L16

opm-simulators: https://github.com/OPM/opm-simulators/blob/master/CMakeLists.txt#L126

Would it be benficial to check out opm-data and make sure these tests are run as part of the Jenkins based PR building?

**Comment by akva2** [comment]
Sure. Since opm data means a lot of network traffic i decided on a separate trigger to execute norne/spe/polymer in simulators but doing this always is trivial to add if that is what is desired. As a prerequisite the integration test suite should be extended in simulators though imo as only spe1 is covered.

**Comment by joakim-hove** [comment]
> if that is what is desired

For the parser I would like this to be enabled; for the simulators others should voice their opinion both whether this should be applied at all, and to what extent the integration test should be extended.

**Comment by alfbr** [comment]
We have limited amount of resources on the jenkins server, I will need a couple of days to investigate this.
