### ISSUE TITLE
Problems with the UNRST file

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-simulators#753]
I am running a case in OPM and I noticed  that the .UNRST file opens normally in Resinsight when you run the case for the first time.  When you run the case again (without deleting the UNRST file) the restart file does not seem to be overwritten but appended at the end and the dynamic properties are not displayed graphically.  In order to recover the properties you have to delete the file and run  the case again.

**Comment by jokva** [comment]
I have an immediate feeling this is a revitalisation bug more than anything. Can you apply a patch to opm-output and try again for me?

**Comment by jokva** [comment]
Actually, can you tell us a bit more about this file? Do you request step 0 not being added to the restart file?

**Comment by dlmorenob** [comment]
I am using the UNIFIN and UNIFOUT keywords meanwhile.  I am testing the field is actually providing the same solution as in Eclipse to be able to continue.  Then I am using the keywords 

RPTSCHED
 FIP /

and

RPTRST
 'BASIC=1' /

and when I run the simulation the first time I obtain the following figure.
![fig1](https://cloud.githubusercontent.com/assets/9252709/16619138/798ae32c-4352-11e6-9a7b-a84337df4f1b.png)

I run the datafile again in flow and you can see the UNRST file is doubling its size
![fig2](https://cloud.githubusercontent.com/assets/9252709/16619156/91c9d204-4352-11e6-99d1-354c4016bd09.png)

I do it again and the file increases its size even more and you cannot see the dynamic data on Resinsight

![fig3](https://cloud.githubusercontent.com/assets/9252709/16619175/b22c4270-4352-11e6-90b5-e0cb42aae724.png)

Finally, I delete only the UNRST file and run it again and I see the file has the correct size and the dynamic properties are displayed on Resinsight.

![fig4](https://cloud.githubusercontent.com/assets/9252709/16619211/cf4d522c-4352-11e6-9e36-d5e2eba55ee8.png)

**Comment by jokva** [comment]
The reason I'm asking is because I noticed that the check in opm-output that determines whether or not we should open a new file or append (which when the file isn't there is equivalent to opening a new) only checks if it is at timestep 0. If you've requested the first timestep to not be written then this would always fail and would always prefer append.

I'll apply a supert quick hack in opm-output - if it fixes your problem the source is identified.

**Comment by jokva** [comment]
Can you apply https://github.com/OPM/opm-output/pull/59 and recompile output and see what happens please?

**Comment by dlmorenob** [comment]
There is a semicolon missing on patch 59 at line 195 of the EclipseWriter.cpp file.  Once it's fix the patch worked.  The file is been written correctly now and the properties can be seen in Resinsight.  Thank you.

![fig5](https://cloud.githubusercontent.com/assets/9252709/16622125/81c90bca-435e-11e6-8b97-79e6a7b21da0.png)

**Comment by jokva** [comment]
Oh right, my bad.

Well, that confirms my suspicion. I'll try to figure out an actual solution to this, but for now you can just use this patch if it fixes your workflow.

Thanks for the report!

**Comment by dlmorenob** [comment]
ok.  Thanks.

**Comment by blattms** [comment]
@jokva Please also keep in mind the restart functionality. While it seems currently broken to me, we might not want to break it further.

I am not sure how the restart functionality is supposed to work, but I would assume that the steps before the restart should be kept and the rest should be overwritten. I am also wondering what happens if we set a different output_dir for a restart.

**Comment by jokva** [comment]
> ok. Thanks. Should I close the report then?

That's not necessary. We'll close the report when the issue is actually fixed.

> Please also keep in mind the restart functionality. While it seems currently broken to me, we might not want to break it further.

It's my understanding that restart support always has been rather flaky and not really ever working.


> I am not sure how the restart functionality is supposed to work, but I would assume that the steps before the restart should be kept and the rest should be overwritten. I am also wondering what happens if we set a different output_dir for a restart.

Neither am I (any Eclipse peeps might want to shed light on this), but it's obvious that we need some improvement here regardless.

The code is in simulators, but I'm pretty sure that if we attempt to restart from a restart file, every restart step from 0 up until the point of restart is re-written, so if a different output_dir is chosen then it'd effectively be a copy. I might be wrong of course, but I seem to recall stumbling over that going through the simulator. If it does that then there's no reason for output to distinguish between starting-from-zero and start-from-restart, and it's really something output shouldn't have to be aware of either. That's application logic, not library logic.

**Comment by atgeirr** [comment]
> It's my understanding that restart support always has been rather flaky and not really ever working.

I believe it has been working, and used extensively by @totto82 when testing, although he would be the best to answer that.

**Comment by dlmorenob** [comment]
If I may say.  I guess the restart files are created or appended according to the RESTART keyword.  If there is no such keyword the file should all be rewritten.  If there is, appended at the end depending on the RESTART position alone.  I have used restart files in Eclipse and I think they work fine.

**Comment by jokva** [comment]
Restart files being written is governed by `RPTSCHED` or `RPTRST`. With `UNIFOUT` specified it the restart file will *surely* be overwritten. If the overwrite happens on the first write (in case you'd cancel the simulation early) or on application I'm unsure of now, but just overwrite everything on application startup is surely easiest. The XNNN restart files won't be overwritten unless output is re-requested on that timestep (but if it is then its results should surely be the same so it's really only a timestamp update in effect).

**Comment by jokva** [comment]
@dlmorenob Can you apply https://github.com/OPM/opm-output/pull/61? It should be the better fix to your problem.

**Comment by dlmorenob** [comment]
I'm away from my laptop now.  I'll do it in the evening. I'll let you know.

**Comment by dlmorenob** [comment]
I have tested the patch and it seems to work fine.  The UNRST file does not grow when you run the case again and you can visualize the dynamic properties on Resinsight. Thank you.
