### ISSUE TITLE
What is the current status of the restart mechanism working now?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#810]
It looks like SPE1 or SPE9 is fine. 

I tried with Norne, it could not get convergent for the first report step. For the model-2,  it reports could not find the report step 10 (I specified 10 in the RESTART deck) in the UNRST file. 

Before I try more, I would like to know if anyone are using the RESTART mechanism for debugging purpose for Norne and model-2 and if they are working well?

Thanks.

**Comment by joakim-hove** [comment]
> What is the current status of the restart mechanism working now?

That is a surprisingly difficult problem to answer. My take on the
situation is that restart basically works - but there are at least two
known problems which affect precision in the initial step after the restart:

   1. We do not store the state of the dynamic timestepper - so the initial
   steplength chosen by the timestep algorithm will in general not agree with
   the timestep chosen in the non-restarted case.
   2. We do not store the currently active control, so if some constraints
   have been violated, and the simulator was not on the default control when
   writing the restart file that will not be picked up.



I tried with Norne, it could not get convergent for the first report step.
>

I would assume this is due to mentioned problems 1 and/or 2.



> For the model-2, it reports could not find the report step 10 (I specified
> 10 in the RESTART deck) in the UNRST file.
>

OK - but is there a step 10 in the restart file? To simplify this I would
reccommend removing the UNIFON & UNIFOUT keywords from the .DATA file -
then you will get restart files as CASE.Xnnnn - and there is no uncertainty
as to which report steps you have available for restart. Alternatively you
can use the ert application "ecl_unpack.x CASE.UNRST" to split the unified
restart file into multiple non unified files.


Jaokim

**Comment by GitPaean** [comment]
> OK - but is there a step 10 in the restart file? To simplify this I would
reccommend removing the UNIFON & UNIFOUT keywords from the .DATA file -
then you will get restart files as CASE.Xnnnn - and there is no uncertainty
as to which report steps you have available for restart. Alternatively you
can use the ert application "ecl_unpack.x CASE.UNRST" to split the unified
restart file into multiple non unified files.

Good point. The restart output happens at the 0, 8, 27, 45 .... steps. At least for the beginning part, I did not find what setup makes the thing this way. The tool `ecl_upack.x` is very helpful. 

Anyway, when I run the code, it shows the keyword `RPTSCHED` is not supported yet. I want to know, for the restart file output, can we specify what we want to output (maybe through keyword `RPTRST`?) or flow just output the same thing all the time?

**Comment by GitPaean** [comment]
With model-2, when specifying with the currect restart report step, the flow does not complain that no report step in the UNRST file, instead, it gives a error. 

```
================ Starting main simulation loop ===============


Catchpoint 1 (exception thrown), 0x00007ffff577d8bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) backtrace 
#0  0x00007ffff577d8bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff57a6082 in std::__throw_bad_alloc() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000007e443d in __gnu_cxx::new_allocator<double>::allocate (this=<optimized out>, __n=18446744073709551615) at /usr/include/c++/5/ext/new_allocator.h:102
#3  std::allocator_traits<std::allocator<double> >::allocate (__a=..., __n=18446744073709551615) at /usr/include/c++/5/bits/alloc_traits.h:491
#4  std::_Vector_base<double, std::allocator<double> >::_M_allocate (this=<optimized out>, __n=18446744073709551615) at /usr/include/c++/5/bits/stl_vector.h:170
#5  std::vector<double, std::allocator<double> >::_M_range_initialize<double const*> (__last=0x17435620, __first=0x17435628, this=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:1287
#6  std::vector<double, std::allocator<double> >::_M_initialize_dispatch<double const*> (__last=0x17435620, __first=0x17435628, this=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:1263
#7  std::vector<double, std::allocator<double> >::vector<double const*, void> (__a=..., __last=0x17435620, __first=0x17435628, this=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:404
#8  Opm::(anonymous namespace)::restoreOPM_XWEL (num_phases=<optimized out>, num_wells=<optimized out>, file=0xaac1b40) at /home/kaib/OPM-devel/debug/opm-output/opm/output/eclipse/EclipseReader.cpp:141
#9  Opm::init_from_restart_file (es=..., numcells=<optimized out>) at /home/kaib/OPM-devel/debug/opm-output/opm/output/eclipse/EclipseReader.cpp:176
#10 0x00000000005eaa91 in Opm::BlackoilOutputWriter::initFromRestartFile<UnstructuredGrid> (this=0x13f27260, phaseusage=..., permeability=permeability@entry=0x217ec9a0, grid=..., simulatorstate=..., wellstate=...)
    at /home/kaib/OPM-devel/debug/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp:371
```

If there is someone can share some their experience with model-2 restart, it will be greatly appreciated.

**Comment by joakim-hove** [comment]
> the flow does not complain that no report step in the UNRST file, instead, it gives a error.

Ahhh - that is hardly progress. It is on the list - don't hold your breath though.
