### ISSUE TITLE
Change 'Error' warning to 'Problem'

### ISSUE THREAD

**Issue by hnqing369** [OPM/opm-simulators#824]
When there are convergence failures, the warning message shows 'Error: Solver convergence failed', while certain number of convergence problems is normally tolerated, it is better to change the message to 'Problem: Solver convergence failed', to avoid the confusion that serious errors are frequently happening through the simulation.

**Comment by blattms** [comment]
Well, I agree but that is not an easy task.

The problem is that OPM_THROW does print this message and logs it to the files. That seems a bit unfortunate as it treats every exception as an error and logs them unconditionally. This also means that each process logs and ouputs them.

I guess we should refactor the code such OPM_THROW really only throws and the logging is decided by the calling code. This is also the only way to make these messages appear only once in parallel runs.

**Comment by atgeirr** [comment]
This has been resolved (not exactly as outlined here though). The current version categorizes such failures as Problem, not Error.
