### ISSUE TITLE
AMG will not be used by interleaved system if UMFPack is there

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#962]
I just stumbled over this, but it has been there (albeit in  another file) since February. In [ISTLSolver.hpp line 208](/OPM/opm-simulators/blob/28c36ef949c340755b0f38ff25b592f627f05c0c/opm/autodiff/ISTLSolver.hpp#L208) AMG is switched off if UMFPack is present. If you have SuperLU but not UMFPack the code will not compile with errors like
```

/home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/NewtonIterationBlackoilInterleaved.cpp:494:1:   required from here
/usr/include/dune/istl/paamg/amg.hh:512:15: error: new initializer expression list treated as compound expression [-fpermissive]
               solver_.reset(new DIRECTSOLVER<typename M::matrix_type>(matrices_->ma
               ^
/usr/include/dune/istl/paamg/amg.hh:512:15: error: no matching function for call to ‘Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >::SuperLU(bool)’
/usr/include/dune/istl/paamg/amg.hh:512:15: note: candidates are:
In file included from /usr/include/dune/istl/paamg/amg.hh:13:0,
                 from /home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/CPRPreconditioner.hpp:41,
                 from /home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/NewtonIterationBlackoilInterleaved.cpp:28:
/usr/include/dune/istl/superlu.hh:80:9: note: constexpr Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >::SuperLU()
   class SuperLU
         ^
/usr/include/dune/istl/superlu.hh:80:9: note:   candidate expects 0 arguments, 1 provided
/usr/include/dune/istl/superlu.hh:80:9: note: constexpr Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >::SuperLU(const Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >&)
/usr/include/dune/istl/superlu.hh:80:9: note:   no known conversion for argument 1 from ‘bool’ to ‘const Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >&’
/usr/include/dune/istl/superlu.hh:80:9: note: constexpr Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >::SuperLU(Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >&&)
/usr/include/dune/istl/superlu.hh:80:9: note:   no known conversion for argument 1 from ‘bool’ to ‘Dune::SuperLU<Dune::BCRSMatrix<Dune::MatrixBlock<double, 1, 1>, std::allocator<Dune::MatrixBlock<double, 1, 1> > > >&&’
```
Both SuperLU and UMFPack can only be used with `BCRSMatrix<FieldMatrix<ctype,n,m>>`. Unfortunately, OPM seems to use Dune::MatrixBlock instead. This issue is there for both legacy and ebos. The class was probably introduced as FieldMatrix::invert got unstable) when DenseMatrix was inroduced upstream. Somehow the specialized invertion algorithms for small matrices were lost.

I have an idea how we can fix this and will cook up a patch

**Comment by blattms** [comment]
Well, what do you know. We are using float as the scalar type, somehow. Weired.

**Comment by blattms** [comment]
I wonder how much runtime we save by switching to float. Does anybody have some insight? (flow_ebos does not do that switching)

**Comment by dr-robertk** [comment]
This is a bug in dune-istl due to the sloppy UMFPACK/SuperLU bindings. The bug was recently fixed in dune 2.5. However, if you disable float, then it should work fine.

**Comment by andlaus** [comment]
> (flow_ebos does not do that switching)

yeah. the ebos part currently only linearizes the reservoir equations without the wells. everything else is done by the flow part...

**Comment by blattms** [comment]
@dr-robertk I beg to differ. I do not see how this can have been fixed dune. UMFPack usually has no float bindings and for SuperLU you have to use an additional preprocessor define. Even with this there is no way around using #963.

@andlaus ??? What is the connection with the wells here?

**Comment by blattms** [comment]
@dr-robertk How do I disable float at compile time?

**Comment by dr-robertk** [comment]
@blattms: Well, UMFPACK does not support float, fine. But when AMG is selected with BCRSMatrix< float > then the whole code does not compile. That was the problem. It's fine that UMFPACK can only be selected when field_type=double. This is what was fixed in dune2.5. So what I was saying is, that AMG is essentially only available for field_type=double when HAVE_UMFPACK is 1 in dune 2.4. 
float can be disabled by changing lines 476-478 in NewtonIterationBlackoilInterleaved.cpp.

**Comment by andlaus** [comment]
> @andlaus ??? What is the connection with the wells here?

ebos instructed to disable the wells (https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/BlackoilModelEbos.hpp#L85 ) and in the assemble() method, the modifications of the residual and its Jacobian due to the wells are later bolted on (https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/BlackoilModelEbos.hpp#L395 )

it's definitely not very nice to do it this way, but IMO it's not going to be the permanent solution.

**Comment by atgeirr** [comment]
I am not sure what to do about this issue. As far I can understand the root problem is that the direct solvers (UMFPACK, SuperLU) do not support float (easily, or at all). Since we need this for solving the coarsest level of an AMG hierarchy (mostly, at least) we cannot use AMG with float.

Always using the double version of the direct solvers seems to me to be the solution, is that not feasible?

**Comment by andlaus** [comment]
did we merge work around here? I vaguely remember something...

**Comment by blattms** [comment]
No, this is still there. It just moved down to line [252](/OPM/opm-simulators/blob/29f3b86ef0382fab13306112e05a4258e8bbde08/opm/autodiff/ISTLSolver.hpp#L252).

**Comment by blattms** [comment]
Closing as this is resolved by refactoring.
