### ISSUE TITLE
Production Through an Injector

### ISSUE THREAD

**Issue by chewson** [OPM/opm-simulators#970]
Perhaps this is because I'm using an older version (2016.10), but if a set point for an injection well is too low to actually inject anything, the well will back produce from the reservoir instead of shutting itself off. Is there any work around/fix to this?

Chris

**Comment by atgeirr** [comment]
Not 100% sure what you mean by:

> if a set point for an injection well is too low to actually inject anything, the well will back produce

but I'll assume you have set a BHP limit for an injector that is below the reservoir pressure? Off the top of my head I am not sure if it will (or even should) help, but disallowing cross-flow in that well could change behaviour. Have you tried that?

I assume the limits are coming from some automated procedure, so it is not feasible to change them manually?

**Comment by totto82** [comment]
Currently there is no other way to prevent "producing injectors" than to set the injection rate to zero in that well. I don't think disallowing cross-flow will work. We are however working on a new and faster implementation where this issue is solved. The new version is available in the current master under the name flow_ebos, and is scheduled to be part of the next release. (2016.04)
