### ISSUE TITLE
can't install OPM 2016.10 on ubuntu 14.04 but instead 2015.10 gets installed

### ISSUE THREAD

**Issue by innovate-data** [OPM/opm-simulators#993]
Hi 

I followed the procedure to install OPM 2016.10 (http://opm-project.org/?page_id=245) on ubuntu linux 14.04.  Instead of 2016.10 2015.10 got installed. Also "sudo apt-get install libopm-simulators-bin" command doesn't work as it can't find libopm-simulators instead it I had to install libopm-autodiff1-bin .
What I am doing wrong ??

**Comment by andlaus** [comment]
welcome! I use the git versions, and I did not do the packages, so take this with a grain of salt: judging from https://launchpad.net/~opm/+archive/ubuntu/ppa/+packages , it looks like the package is called `libopm-simulators1-bin`. (mind the `1`; @akva2 is authoritative here.) If this turns out to be the case, we need to adapt the website...

**Comment by atgeirr** [comment]
Welcome to OPM!

> Also "sudo apt-get install libopm-simulators-bin" command doesn't work as it can't find libopm-simulators instead it I had to install libopm-autodiff1-bin

The opm-autodiff module was renamed to opm-simulators some time ago, so to me this indicates that the package repository cache could be outdated. Try issuing this command (again):
```
sudo apt-get update
```
and see if you get something reasonable from
```
apt-cache search opm-simulators
```

You might have to uninstall the opm-autodiff package before installing the opm-simulators package (I am not sure if it "knows" that it is an updated version or not). I think the trailing "1" should not be significant.

**Comment by innovate-data** [comment]
thanks for reply

i looked at 2016 installations they are for amd64 not for i386. i have ubuntu 32 bit.

**Comment by andlaus** [comment]
> i have ubuntu 32 bit.

ah, I was unaware of the fact that anybody chose to install 32 bit x86 linux after ca. 2010 ;)

did you get the issue solved?

**Comment by atgeirr** [comment]
I think we stopped building 32 bit versions, so unfortunately you must then build from source. I don't remember the details of why we stopped, but I think there was an issue with some of the packages OPM depends on (perhaps @akva2 remembers). Is there a strong reason why you need to be on 32 bit Ubuntu, or would the 64 bit distribution be an alternative for you?

**Comment by innovate-data** [comment]
I installed OPM 2016.10 on ubuntu 64 bit, works fine thanks.

Another request are you guys planning to have a windows installer like resinsight my friends were asking ?

Thanks

**Comment by atgeirr** [comment]
> I installed OPM 2016.10 on ubuntu 64 bit, works fine thanks.

Good to hear that it worked for you! I have updated the installation instructions on the website to clearly state that the packages are for the 64 bit version.

> planning to have a windows installer

I'll add to @andlaus' reply only this:
 - since some libraries we depend on (such as linear solvers and other components from Dune) are not supported on Windows it would be a lot of work to achieve this
 - Flow and other OPM programs will run quite well in a virtual machine, we have a tutorial for that: http://opm-project.org/?page_id=294

**Comment by innovate-data** [comment]
hi all
thanks . i also can run OPM on windows 10 native ubuntu installation. this is quite helpful as all the files are in Windows environment and resinsight can access it

**Comment by atgeirr** [comment]
That is very interesting, if you could provide the necessary steps we could put instructions on the web site, or even a small tutorial?

**Comment by innovate-data** [comment]
Hi All

I just followed steps by andlaus and installed ubuntu by using bash servive in windows 10 64 bit latest anniversary version. once you install ubuntu 64 bit you just follow steps on the website and i was able to run flow. it is quite useful for using output files in windows environment

**Comment by andlaus** [comment]
that's great news because then the windows port was *much* easier than anticipated ;)
